import {
  address,
  aiCitationSummary,
  alternateName,
  buildImageGalleryJsonLd,
  buildLocalPagesItemListJsonLd,
  buildMenuJsonLd,
  buildRestaurantJsonLd,
  buildWebsiteJsonLd,
  coordinates,
  cuisine,
  dateModified,
  dateModifiedIso,
  displayAddress,
  displayPhone,
  email,
  foundingDate,
  fullAddress,
  localAreas,
  localSeoFacts,
  mapsUrl,
  menuSections,
  nearbyLandmarks,
  openingHours,
  phoneE164,
  sameAsUrls,
  seoPages,
  siteName,
  siteUrl,
  supportedLanguages,
  transitAccess,
  whatsappUrl,
} from "../seo";

export function GET() {
  return Response.json(
    {
      name: siteName,
      alternateName,
      url: siteUrl,
      type: ["Restaurant", "LocalBusiness"],
      lastUpdated: dateModified,
      lastUpdatedIso: dateModifiedIso,
      foundingDate,
      language: "tr-TR",
      supportedLanguages,
      aiCitationSummary,
      schemaOrg: {
        "@context": "https://schema.org",
        "@graph": [
          buildWebsiteJsonLd(false),
          buildRestaurantJsonLd(false),
          buildMenuJsonLd(),
          buildImageGalleryJsonLd(false),
          buildLocalPagesItemListJsonLd(false),
        ],
      },
      contact: {
        phone: displayPhone,
        phoneE164,
        whatsapp: whatsappUrl,
        email,
      },
      address: {
        ...address,
        displayAddress,
        fullAddress,
      },
      geo: {
        latitude: coordinates.latitude,
        longitude: coordinates.longitude,
      },
      mapsUrl,
      openingHours,
      cuisine,
      paymentAccepted: ["Nakit", "Kredi Kartı", "Banka Kartı"],
      priceSignals: {
        traditionalVanBreakfastPerPersonTry: 450,
        sucukluYumurtaTry: 180,
        note: "Fiyatlar yaklaşık bilgidir; güncel fiyat için işletmeyle iletişime geçin.",
      },
      menu: menuSections,
      locationContext: {
        localAreas,
        nearbyLandmarks,
        transitAccess,
      },
      localSeoFacts,
      importantPages: seoPages.map((page) => ({
        title: page.title,
        h1: page.h1,
        url: `${siteUrl}/${page.slug}`,
        description: page.description,
        localIntent: page.localIntent ?? [],
      })),
      sameAs: sameAsUrls,
    },
    {
      headers: {
        "Cache-Control": "public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800",
      },
    },
  );
}
