import {
  address,
  aiCitationSummary,
  alternateName,
  buildGeoCoverageJsonLd,
  buildImageGalleryJsonLd,
  buildLocalPagesItemListJsonLd,
  buildMenuJsonLd,
  buildRestaurantJsonLd,
  buildWebsiteJsonLd,
  coordinates,
  cuisine,
  dateModified,
  dateModifiedIso,
  displayAddress,
  displayPhone,
  email,
  foundingDate,
  fullAddress,
  geoServiceArea,
  geoSearchIntents,
  homeLanguageAlternates,
  internationalTouristFacts,
  localAreas,
  localAreaProfiles,
  localSeoFacts,
  mapsUrl,
  menuSections,
  mobileGeoActions,
  nearbyPlaceProfiles,
  nearbyLandmarks,
  openingHours,
  phoneE164,
  sameAsUrls,
  seoPages,
  siteName,
  siteUrl,
  supportedLanguages,
  transitAccess,
  walkingRouteProfiles,
  whatsappUrl,
} from "../seo";

export function GET() {
  return Response.json(
    {
      name: siteName,
      alternateName,
      url: siteUrl,
      type: ["Restaurant", "LocalBusiness"],
      lastUpdated: dateModified,
      lastUpdatedIso: dateModifiedIso,
      foundingDate,
      language: "tr-TR",
      supportedLanguages,
      supportedLanguagePages: homeLanguageAlternates,
      aiCitationSummary,
      schemaOrg: {
        "@context": "https://schema.org",
        "@graph": [
          buildWebsiteJsonLd(false),
          buildRestaurantJsonLd(false),
          buildMenuJsonLd(),
          buildImageGalleryJsonLd(false),
          buildLocalPagesItemListJsonLd(false),
          buildGeoCoverageJsonLd(false),
        ],
      },
      contact: {
        phone: displayPhone,
        phoneE164,
        whatsapp: whatsappUrl,
        email,
      },
      address: {
        ...address,
        displayAddress,
        fullAddress,
      },
      geo: {
        latitude: coordinates.latitude,
        longitude: coordinates.longitude,
      },
      mapsUrl,
      openingHours,
      cuisine,
      paymentAccepted: ["Nakit", "Kredi Kartı", "Banka Kartı"],
      priceSignals: {
        traditionalVanBreakfastPerPersonTry: 450,
        sucukluYumurtaTry: 180,
        note: "Fiyatlar yaklaşık bilgidir; güncel fiyat için işletmeyle iletişime geçin.",
      },
      menu: menuSections,
      locationContext: {
        geoServiceArea,
        localAreas,
        localAreaProfiles,
        nearbyPlaceProfiles,
        nearbyLandmarks,
        transitAccess,
        walkingRouteProfiles,
        geoSearchIntents,
        mobileGeoActions,
      },
      localSeoFacts,
      internationalTouristFacts,
      yandexOptimization: {
        russianTouristPage: `${siteUrl}/zavtrak-taksim-stambul`,
        hreflangInHead: true,
        canonicalUrls: true,
        serverRenderedHtml: true,
        note:
          "Russian tourist content is available as crawlable HTML with reciprocal hreflang links in the page head; no Yandex verification token is published because a real token is required.",
      },
      browserOptimization: {
        safari: ["appleWebApp metadata", "apple touch icon", "responsive viewport"],
        chrome: ["manifest", "theme color", "server-rendered content", "structured data"],
      },
      importantPages: seoPages.map((page) => ({
        title: page.title,
        h1: page.h1,
        url: `${siteUrl}/${page.slug}`,
        description: page.description,
        language: page.language ?? "tr-TR",
        localIntent: page.localIntent ?? [],
      })),
      sameAs: sameAsUrls,
    },
    {
      headers: {
        "Cache-Control": "public, max-age=3600, s-maxage=86400, stale-while-revalidate=604800",
      },
    },
  );
}
