export const menuCategoryIds = ["sofra", "sicaklar", "vandan", "icecekler"] as const;

export type MenuCategoryId = (typeof menuCategoryIds)[number];
export type MenuFilterId = "all" | MenuCategoryId;
export type MenuTag = "Öne çıkan" | "Tavsiye" | "Vejetaryen" | "Yeni";

export type MenuCategory = {
  id: MenuCategoryId;
  label: string;
  shortLabel: string;
  description: string;
  image: string;
  imageAlt: string;
};

export type MenuItem = {
  id: string;
  category: MenuCategoryId;
  name: string;
  description: string;
  story: string;
  price: string;
  priceNote?: string;
  image: string;
  imageAlt: string;
  tags: MenuTag[];
  details: string[];
};

export const menuCategories: MenuCategory[] = [
  {
    id: "sofra",
    label: "Van Sofraları",
    shortLabel: "Sofralar",
    description: "Paylaşmak için kurulan serpme sofralar ve kahvaltı tabakları.",
    image: "/images/hero-parallax/overhead-classic.webp",
    imageAlt: "Kuşbakışı kurulmuş geleneksel Van kahvaltısı sofrası",
  },
  {
    id: "sicaklar",
    label: "Bakır Sahanlar",
    shortLabel: "Sıcaklar",
    description: "Mutfaktan çıktığı anda, tereyağı hâlâ cızırdarken masaya gelenler.",
    image: "/images/sucuk-egg.webp",
    imageAlt: "Bakır sahanda sıcak sucuklu yumurta",
  },
  {
    id: "vandan",
    label: "Van’dan Gelenler",
    shortLabel: "Van’dan",
    description: "Otlu peynirden keteye, yöre hafızasını taşıyan kahvaltılıklar.",
    image: "/images/kete-detail.jpg",
    imageAlt: "Kat kat dokulu geleneksel Van ketesi",
  },
  {
    id: "icecekler",
    label: "Çay & Kahve",
    shortLabel: "İçecekler",
    description: "Sofranın ritmini koruyan taze çaylar ve Kafka Cafe kahveleri.",
    image: "/images/tea-service.webp",
    imageAlt: "İnce belli bardaklarda taze çay servisi",
  },
];

export const menuItems: MenuItem[] = [
  {
    id: "geleneksel-van-kahvaltisi",
    category: "sofra",
    name: "Geleneksel Van Kahvaltısı",
    description: "Otlu peynir, murtuğa, kavut, cacık, kete, bal-kaymak ve sınırsız çay.",
    story: "1978’den beri masanın ortasına birlikte yenmek üzere kurduğumuz Van sofrası. Yöresel ürünler, ev yapımı dokunuşlar ve sıcak bakır sahanlarla tamamlanır.",
    price: "₺450",
    priceNote: "kişi başı · en az 2 kişilik",
    image: "/images/breakfast-spread.webp",
    imageAlt: "Peynirler, sıcak sahanlar ve çayla kurulmuş geleneksel Van kahvaltısı sofrası",
    tags: ["Öne çıkan", "Tavsiye"],
    details: ["En az iki kişilik servis", "Sınırsız taze çay", "Günlük hazırlanan eşlikçiler"],
  },
  {
    id: "iki-kisilik-van-sofrasi",
    category: "sofra",
    name: "İki Kişilik Van Sofrası",
    description: "Sıcak sahan, yöresel peynirler, ev reçelleri ve demli çayla kompakt sofra.",
    story: "İki kişilik daha derli toplu bir Van sofrası isteyen misafirlerimiz için sıcak ve soğuk lezzetleri dengeli porsiyonlarda bir araya getiriyoruz.",
    price: "₺860",
    priceNote: "iki kişilik",
    image: "/images/hero-parallax/overhead-classic.webp",
    imageAlt: "İki kişilik hazırlanmış Van kahvaltısı masası",
    tags: ["Yeni"],
    details: ["İki kişilik servis", "Bir sıcak sahan", "İki kişiye sınırsız çay"],
  },
  {
    id: "peynir-zeytin-seckisi",
    category: "sofra",
    name: "Peynir & Zeytin Seçkisi",
    description: "Van otlu peyniri, günlük peynirler, yeşil ve siyah zeytin.",
    story: "Van kahvaltısının karakterini önce otlu peynir kurar. Farklı dokudaki peynirleri ve zeytinleri her lokmada denge sağlayacak biçimde aynı tabakta buluşturuyoruz.",
    price: "₺220",
    image: "/images/hero-float/cheese-platter.webp",
    imageAlt: "Van otlu peyniri, farklı peynirler ve zeytinlerden oluşan kahvaltı tabağı",
    tags: ["Vejetaryen"],
    details: ["Van otlu peyniri", "Günlük peynir seçkisi", "Yeşil ve siyah zeytin"],
  },
  {
    id: "bal-kaymak-recel",
    category: "sofra",
    name: "Bal, Kaymak & Ev Reçelleri",
    description: "Süzme bal, manda kaymağı ve mevsime göre hazırlanan iki ev reçeli.",
    story: "Sofranın tatlı tarafını tek bir yoğun tada bırakmıyoruz. Süzme balı kaymakla, ev reçellerini ise sıcak hamur işleriyle eşleştiriyoruz.",
    price: "₺195",
    image: "/images/hero-float/apricot-jam-bowl.webp",
    imageAlt: "Küçük kasede ev yapımı kayısı reçeli, bal ve kaymak sunumu",
    tags: ["Vejetaryen"],
    details: ["Süzme bal", "Manda kaymağı", "İki çeşit mevsimlik ev reçeli"],
  },
  {
    id: "sucuklu-yumurta",
    category: "sicaklar",
    name: "Sahanda Sucuklu Yumurta",
    description: "Kasap sucuğu ve köy yumurtası, bakır sahanda sıcak servis.",
    story: "Sucuk dilimlerini önce bakır sahanda çeviriyor, köy yumurtasını ardından ekliyoruz. Sarısı akışkan, kenarları sıcak kalacak anda servis ediyoruz.",
    price: "₺180",
    image: "/images/sucuk-egg.webp",
    imageAlt: "Bakır sahanda sucuk dilimleri ve akışkan sarılı yumurta",
    tags: ["Öne çıkan", "Tavsiye"],
    details: ["Kasap sucuğu", "Köy yumurtası", "Bakır sahanda servis"],
  },
  {
    id: "murtuga",
    category: "sicaklar",
    name: "Murtuğa",
    description: "Un, tereyağı ve yumurtayla hazırlanan doyurucu Van klasiği.",
    story: "Murtuğa, az malzemeyle güçlü bir sofra kuran Van mutfağının en güzel örneklerinden. Tereyağının kokusu çıkana kadar pişirip sıcak servis ediyoruz.",
    price: "₺160",
    image: "/images/hero-parallax/overhead-feast.webp",
    imageAlt: "Bakır sahanlar ve yöresel tabaklarla kurulu Van kahvaltısı",
    tags: ["Tavsiye", "Vejetaryen"],
    details: ["Tereyağı", "Yumurta", "Geleneksel Van tarifi"],
  },
  {
    id: "kavut",
    category: "sicaklar",
    name: "Kavut",
    description: "Kavrulmuş un ve tereyağıyla hazırlanan tatlı, tok kıvamlı sıcak.",
    story: "Kavutun sade görünümünün arkasında uzun bir yöre geleneği var. Kavrulmuş unun tok aromasını dengeli bir kıvamla masaya getiriyoruz.",
    price: "₺145",
    image: "/images/hero-parallax/spread-close.webp",
    imageAlt: "Kahvaltı sofrasında bakır sahan ve yöresel Van lezzetleri",
    tags: ["Vejetaryen"],
    details: ["Kavrulmuş un", "Tereyağı", "Sıcak servis"],
  },
  {
    id: "menemen",
    category: "sicaklar",
    name: "Tereyağlı Menemen",
    description: "Domates, köy biberi ve yumurta; bakır sahanda sulu kıvamda.",
    story: "Domates ve biberi tereyağında kısa süre çevirip yumurtayı en son ekliyoruz. Ekmeği sahana uzatacak kadar sulu, tadı yoğun kalıyor.",
    price: "₺175",
    image: "/images/hero-float/sucuk-egg-pan.webp",
    imageAlt: "Bakır sahanda sıcak tereyağlı menemen",
    tags: ["Vejetaryen"],
    details: ["Köy biberi", "Günlük domates", "Bakır sahanda servis"],
  },
  {
    id: "kavurmali-yumurta",
    category: "sicaklar",
    name: "Kavurmalı Yumurta",
    description: "Dana kavurma ve köy yumurtası, tereyağlı bakır sahanda.",
    story: "Yumuşak dana kavurmayı tereyağında ısıtıp yumurtayla bir araya getiriyoruz. Güçlü, sıcak ve paylaşmaya uygun bir sahan.",
    price: "₺240",
    image: "/images/hero-parallax/kavurma-pan.webp",
    imageAlt: "Bakır tavada yumurtayla pişirilmiş dana kavurma",
    tags: ["Yeni"],
    details: ["Dana kavurma", "Köy yumurtası", "Tereyağlı pişirim"],
  },
  {
    id: "otlu-peynirli-omlet",
    category: "sicaklar",
    name: "Otlu Peynirli Omlet",
    description: "Van otlu peyniri ve taze yeşillikle yumuşak kıvamlı omlet.",
    story: "Otlu peynirin belirgin aromasını yumuşak pişmiş yumurta ve taze yeşillikle dengeliyoruz. Masaya sıcak ve kabarık geliyor.",
    price: "₺190",
    image: "/images/hero-float/omelette-plate.webp",
    imageAlt: "Yeşillik ve zeytinle servis edilen otlu peynirli omlet",
    tags: ["Vejetaryen"],
    details: ["Van otlu peyniri", "Köy yumurtası", "Taze yeşillik"],
  },
  {
    id: "van-otlu-peyniri",
    category: "vandan",
    name: "Van Otlu Peyniri",
    description: "Yöresel otların aromasıyla olgunlaşan Van sofrasının imza peyniri.",
    story: "Sofraya koyduğumuz otlu peynir yalnızca bir eşlikçi değil, Van kahvaltısının hafızasıdır. Güçlü aromasını taze yeşillik ve çayla dengeleriz.",
    price: "₺165",
    image: "/images/hero-float/cheese-platter.webp",
    imageAlt: "Dilimlenmiş Van otlu peyniri ve kahvaltılık peynir tabağı",
    tags: ["Öne çıkan", "Vejetaryen"],
    details: ["Yöresel ot aroması", "Olgunlaştırılmış peynir", "Van’dan gelen lezzet"],
  },
  {
    id: "kete",
    category: "vandan",
    name: "Van Ketesi",
    description: "Kat kat dokulu, tereyağlı içli yöresel hamur işi.",
    story: "Ketenin katlarını dağıtmadan, içini yumuşak tutacak şekilde ısıtıyoruz. Bal ve kaymakla buluştuğunda sofranın en sakin ama akılda kalan lokmalarından biri olur.",
    price: "₺120",
    image: "/images/kete-detail.jpg",
    imageAlt: "Katmanlı dokusu görünen geleneksel Van ketesi",
    tags: ["Vejetaryen"],
    details: ["Tereyağlı hamur", "Kat kat doku", "Ilık servis"],
  },
  {
    id: "pisi-sepeti",
    category: "vandan",
    name: "Sıcak Pişi Sepeti",
    description: "Dışı hafif çıtır, içi yumuşak dört adet sıcak pişi.",
    story: "Pişileri siparişle kızartıyor, yağını dinlendirip sıcak servis ediyoruz. Bal-kaymak ve peynir tabaklarının en sevilen eşlikçisi.",
    price: "₺135",
    priceNote: "4 adet",
    image: "/images/hero-parallax/table-pisi.webp",
    imageAlt: "Ahşap sunum tahtasında sıcak pişiler ve kahvaltı tabağı",
    tags: ["Tavsiye", "Vejetaryen"],
    details: ["Dört adet", "Siparişle hazırlanır", "Sıcak servis"],
  },
  {
    id: "van-cacigi",
    category: "vandan",
    name: "Van Cacığı",
    description: "Süzme yoğurt, salatalık ve taze otlarla yoğun kahvaltılık cacık.",
    story: "Van cacığını içecek kıvamında değil, ekmeğe sürülecek yoğunlukta hazırlıyoruz. Taze otlar ve salatalıkla sofraya ferahlık getiriyor.",
    price: "₺110",
    image: "/images/hero-float/greens-platter.webp",
    imageAlt: "Taze yeşilliklerle servis edilen yoğun kıvamlı Van cacığı",
    tags: ["Vejetaryen"],
    details: ["Süzme yoğurt", "Taze salatalık", "Mevsim yeşillikleri"],
  },
  {
    id: "simit-ekmek-sepeti",
    category: "vandan",
    name: "Simit & Sıcak Ekmek",
    description: "Çıtır simit, sıcak ekmek ve tereyağıyla sofra tamamlayıcısı.",
    story: "Peynir, reçel ve sıcak sahanlar arasında geçişi sağlayan ekmek sepetini sıcak tutarak servis ediyoruz.",
    price: "₺95",
    image: "/images/hero-float/simit-board.webp",
    imageAlt: "Ahşap tahta üzerinde simit ve sıcak kahvaltılık ekmekler",
    tags: ["Vejetaryen"],
    details: ["Çıtır simit", "Sıcak ekmek", "Tereyağı"],
  },
  {
    id: "sinirsiz-cay",
    category: "icecekler",
    name: "Sınırsız Taze Çay",
    description: "İnce belli bardakta, sofra boyunca tazelenen demli çay.",
    story: "Bizim için kahvaltının süresini saat değil, çayın demi belirler. Sofra boyunca bardakları taze çayla yenileriz; sohbet aceleye gelmez.",
    price: "₺85",
    priceNote: "serpme kahvaltıya dahil",
    image: "/images/tea-service.webp",
    imageAlt: "İnce belli bardaklarda servis edilen taze demlenmiş Türk çayı",
    tags: ["Tavsiye", "Vejetaryen"],
    details: ["Taze dem", "Sınırsız servis", "İnce belli bardak"],
  },
  {
    id: "turk-kahvesi",
    category: "icecekler",
    name: "Geleneksel Türk Kahvesi",
    description: "Bakır cezvede yavaş pişirilen, köpüklü Türk kahvesi.",
    story: "Kafka Cafe köşemizde kahveyi acele etmeden, köpüğünü koruyarak pişiriyoruz. Uzayan kahvaltının ardından küçük ama belirgin bir kapanış.",
    price: "₺95",
    image: "/images/coffee-moment.webp",
    imageAlt: "Kahvaltı sonrasında sunulan köpüklü Türk kahvesi",
    tags: ["Vejetaryen"],
    details: ["Bakır cezvede pişirim", "Köpüklü servis", "Kafka Cafe seçkisi"],
  },
  {
    id: "sutlu-turk-kahvesi",
    category: "icecekler",
    name: "Sütlü Türk Kahvesi",
    description: "Yumuşak içimli, sütle ağır ağır pişirilen Türk kahvesi.",
    story: "Klasik Türk kahvesinin yoğunluğunu sütle yumuşatıyor, köpüğünü koruyarak küçük fincanda servis ediyoruz.",
    price: "₺105",
    image: "/images/og/kafka-cafe.jpg",
    imageAlt: "Sütle hazırlanmış köpüklü Türk kahvesi fincanı",
    tags: ["Yeni", "Vejetaryen"],
    details: ["Sütle pişirim", "Yumuşak içim", "Köpüklü servis"],
  },
  {
    id: "filtre-kahve",
    category: "icecekler",
    name: "Günün Filtre Kahvesi",
    description: "Kafka Cafe’nin günlük çekirdeğiyle dengeli ve temiz fincan.",
    story: "Günün çekirdeğini aromasını örselemeden demliyor, kahvaltı sonrasında uzun sohbetlere eşlik edecek dengeli bir fincan hazırlıyoruz.",
    price: "₺120",
    image: "/images/terrace-tea.webp",
    imageAlt: "Teras masasında servis edilen sıcak filtre kahve",
    tags: ["Vejetaryen"],
    details: ["Günlük çekirdek", "Taze demleme", "Kafka Cafe seçkisi"],
  },
  {
    id: "ev-limonatasi",
    category: "icecekler",
    name: "Ev Yapımı Limonata",
    description: "Taze limon, az şeker ve mevsim otlarıyla ferah içim.",
    story: "Limon kabuğunun aromasını taze suyla buluşturup şekerini baskın olmayacak ölçüde tutuyoruz. Kahvaltının sıcaklarına serin bir eşlikçi.",
    price: "₺115",
    image: "/images/hero-parallax/tea-tray.webp",
    imageAlt: "Kahvaltı masasında soğuk ev yapımı limonata servisi",
    tags: ["Vejetaryen"],
    details: ["Taze limon", "Az şekerli", "Soğuk servis"],
  },
];

export const menuLastUpdated = "16 Temmuz 2026";
