import { faqItems } from "./seo";

export type SiteLocale = "tr" | "en";

export const englishFaqItems = [
  {
    question: "Where can I have a traditional Turkish breakfast near Taksim?",
    answer:
      "Tarihi Van Kahvaltı Evi serves a traditional Van-style Turkish breakfast on Zambak Street in Beyoğlu, within walking distance of Taksim Square and İstiklal Avenue.",
  },
  {
    question: "What is included in a Van breakfast?",
    answer:
      "A Van breakfast is a shared table of regional cheeses, olives, honey and clotted cream, homemade preserves, breads, hot egg dishes, murtuğa, kavut and freshly brewed Turkish tea. Availability may vary with the season and daily preparation.",
  },
  {
    question: "What are murtuğa and kavut?",
    answer:
      "Murtuğa is a warm Van speciality made with flour, butter and egg. Kavut is a rich, gently sweet dish based on toasted flour and butter. Both are traditionally served as part of the breakfast table.",
  },
  {
    question: "What time is Tarihi Van Kahvaltı Evi open?",
    answer:
      "Tarihi Van Kahvaltı Evi is open every day from 08:00 to 18:00. Please contact the restaurant before travelling on public holidays or with a large group.",
  },
  {
    question: "Where can I see the current menu and prices?",
    answer:
      "The live English menu lists the current shared breakfasts, hot dishes, regional specialities, tea and coffee prices in Turkish lira. Prices and availability can change, so check it shortly before your visit.",
  },
  {
    question: "How can I request a reservation?",
    answer:
      "Call +90 541 525 2868 or send a WhatsApp message. Your table is confirmed only after the restaurant replies.",
  },
] as const;

export const homeMessages = {
  tr: {
    documentLanguage: "tr",
    alternateLanguage: "EN",
    alternateLanguageLabel: "English",
    alternateHref: "/en",
    homeHref: "/#top",
    menuHref: "/menu",
    aboutHref: "/hikayemiz",
    galleryHref: "/#gallery",
    faqHref: "/#faq",
    nav: {
      aria: "Ana menü",
      about: "Hakkımızda",
      menu: "Menü",
      gallery: "Galeri",
      location: "Konum",
      faq: "SSS",
      open: "Menüyü aç",
      close: "Menüyü kapat",
      panelTitle: "Menü",
      home: ["Ana sayfa", "Sıcak sofra açılışı"],
      story: ["Hakkımızda", "Tarihi Rum binası"],
      liveMenu: ["Menü", "Fiyatlar ve içerik"],
      galleryItem: ["Galeri", "Bakır, çay, masa"],
      directions: ["Konum", "Beyoğlu rotası"],
      breakfast: ["Van kahvaltısı", "Yöresel lezzetler ve fiyatlar"],
      internationalGuides: [
        ["/en/blog/turkish-breakfast-istanbul", "English guide", "Traditional Turkish breakfast", "en"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид", "Турецкий завтрак в Стамбуле", "ru"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي", "الفطور التركي في إسطنبول", "ar"],
        ["/ko/blog/istanbul-bal-kaymak", "한국어 가이드", "이스탄불 발 카이막", "ko"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語ガイド", "イスタンブールのバル・カイマク", "ja"],
      ],
      questions: ["Sıkça sorulanlar", "Kısa ve net cevaplar"],
      whatsapp: ["WhatsApp", "Hızlı iletişim"],
      book: "Masada yerini ayırt",
    },
    mobile: {
      aria: "Hızlı işlemler",
      whatsappAria: "WhatsApp üzerinden mesaj gönderin",
      menuAria: "QR menüyü açın",
      menu: "Menü",
      directionsAria: "Haritada yol tarifi alın",
      directions: "Yol Tarifi",
    },
    hero: {
      aria: "Tarihi Van Kahvaltı Evi ana alanı",
      year: "1978'den beri",
      place: "Beyoğlu'nda bir aile sofrası",
      titleLineOne: "Tarihi Van",
      titleLineTwo: "Kahvaltı Evi",
      intro: "Otlu peynir, murtuğa, kavut, sıcak bakır sahanlar ve hep taze çay.",
      floatingAlts: {
        pan: "Bakır sahanda sucuklu yumurta",
        tea: "İnce belli çay",
        simit: "Ahşap tabakta sıcak simit",
        omelette: "Kahvaltı tabağı",
        cheese: "Van peynir tabağı",
        greens: "Taze yeşillik tabağı",
        olives: "Siyah zeytin kasesi",
        jam: "Kayısı reçeli kasesi",
      },
    },
    about: {
      meta: "Hakkımızda",
      title: "Van sofrası,",
      titleEmphasis: "Taksim'de ağır ağır kurulur.",
      lead:
        "Zambak Sokak'ın kendine özgü dokusunda, Van'ın sevilen tatlarını aynı sofrada buluşturuyoruz. Otlu peynirden murtuğaya, sıcak pişiden ev yapımı reçellere her tabak günlük hazırlanır. Bizim için kahvaltı hızlı bir öğün değil; çayın demlendiği, sohbetin uzadığı sakin bir buluşmadır.",
      primaryAction: "Sofrayı keşfet",
      bookingAction: "Masanı ayırt",
      actionsAria: "Hakkımızda bölümü sonraki adımlar",
      principlesAria: "Tarihi Van Kahvaltı Evi'nin sofra yaklaşımı",
      tableAlt: "Kahvaltı sofrasında peynir, reçel ve tahin tabaklarını uzatan eller",
      memoryAlt: "Mekândaki oymalı çerçeveli ayna ve aynaya yansıyan tuğla duvar",
      principles: [
        ["Beyoğlu konumu", "Zambak Sokak'ta; Taksim, İstiklal Caddesi ve M2 metrosuna birkaç adım."],
        ["Günlük emek", "Taze hazırlanan reçeller, sıcak pişiler ve özenle kurulan kahvaltı."],
        ["Van sofrası", "Otlu peynir, murtuğa, kete ve demli çayla yöresel karakter."],
      ],
    },
    gallery: {
      title: "Mekan",
      titleAccent: "anları",
      booking: "Rezervasyon al",
      aria: "Mekan fotoğrafları",
      close: "Galeri kapat",
      previous: "Önceki fotoğraf",
      next: "Sonraki fotoğraf",
      view: "Görüntüle",
      images: [
        ["/images/balcony-breakfast.webp", "Balkonda kahvaltı keyfi"],
        ["/images/sucuk-egg.webp", "Sıcak sahanda sucuklu yumurta"],
        ["/images/hands-table.webp", "Masada paylaşım anları"],
        ["/images/interior-chair.webp", "Tarihi Rum binası iç mekan dokusu"],
        ["/images/tea-service.webp", "Sınırsız taze demlenmiş çay servisi"],
        ["/images/breakfast-spread.webp", "Geleneksel serpme Van sofrası"],
        ["/images/historic-mirror.webp", "Tarihi ayna ve bina detayları"],
        ["/images/terrace-tea.webp", "Teras keyfi ve çay servisi"],
        ["/images/coffee-moment.webp", "Kafka Cafe kahve molası"],
        ["/images/street-table.webp", "Beyoğlu sokaklarında kahvaltı masası"],
      ],
    },
    faq: {
      eyebrow: "Merak edilenler",
      title: "Sıkça Sorulan Sorular",
      intro: "Tarihi Van Kahvaltı Evi ve serpme kahvaltımız hakkında kısa cevaplar.",
      items: faqItems,
    },
    footer: {
      sceneAria: "İstiklal Caddesi’nde nostaljik tramvay, Galata Kulesi ve tarihi Beyoğlu silüeti",
      backToTop: "Başa dön",
      manifesto: "Van kahvaltısı,",
      manifestoEmphasis: "tarihle aynı sofrada.",
      description:
        "1978’den beri süregelen aile yolculuğumuzda, Beyoğlu’nun kalbindeki tarihi Rum binasının dokusunu, bakır sahanların tınısı ve eksilmeyen demli çayımızla buluşturuyoruz.",
      booking: "Masada Yerini Ayırt",
      explore: "Keşfet",
      exploreLinks: [
        ["/menu", "Zengin Menü"],
        ["/van-kahvaltisi", "Van Kahvaltısı Rehberi"],
        ["/van-kahvaltisi-nedir", "Van Kahvaltısı Nedir?"],
        ["/hikayemiz", "1978'den Beri Hikâyemiz"],
        ["/konum", "Beyoğlu ve Taksim Kahvaltı"],
        ["/menu", "Kafka Cafe"],
        ["/konum", "Konum ve Yol Tarifi"],
        ["/#faq", "Sıkça Sorulan Sorular"],
        ["/en", "English Visitor Guide"],
        ["/en/blog/turkish-breakfast-istanbul", "English Breakfast Guide"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Гид на русском"],
        ["/ar/blog/turkish-breakfast-istanbul", "دليل الفطور بالعربية"],
        ["/ko/blog/istanbul-bal-kaymak", "한국어 발 카이막 가이드"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語バル・カイマクガイド"],
      ],
      contact: "Bize Ulaşın",
      whatsapp: "WhatsApp İletişim",
      listedTitle: "2. Derece",
      listedSubtitle: "Tarihi Eser",
      hours: "Her Gün Açığız",
      copyright: "© 2026 Tarihi Van Kahvaltı Evi. Tüm hakları saklıdır.",
      privacy: "Gizlilik Politikası",
      cookies: "Çerez Politikası",
    },
  },
  en: {
    documentLanguage: "en",
    alternateLanguage: "TR",
    alternateLanguageLabel: "Türkçe",
    alternateHref: "/",
    homeHref: "/en#top",
    menuHref: "/en/menu",
    aboutHref: "/en#story",
    galleryHref: "/en#gallery",
    faqHref: "/en#faq",
    nav: {
      aria: "Main navigation",
      about: "Our story",
      menu: "Menu",
      gallery: "Gallery",
      location: "Directions",
      faq: "FAQ",
      open: "Open navigation",
      close: "Close navigation",
      panelTitle: "Explore",
      home: ["Home", "A table waiting in Beyoğlu"],
      story: ["Our story", "A family breakfast house since 1978"],
      liveMenu: ["Live menu", "Current dishes and prices"],
      galleryItem: ["Gallery", "Copper pans, tea and shared tables"],
      directions: ["Directions", "Find us near Taksim"],
      breakfast: ["Van breakfast", "Meet the regional specialities"],
      internationalGuides: [
        ["/en/blog/turkish-breakfast-istanbul", "English guide", "Traditional Turkish breakfast", "en"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид", "Турецкий завтрак в Стамбуле", "ru"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي", "الفطور التركي في إسطنبول", "ar"],
        ["/ko/blog/istanbul-bal-kaymak", "한국어 가이드", "이스탄불 발 카이막", "ko"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語ガイド", "イスタンブールのバル・カイマク", "ja"],
      ],
      questions: ["Visitor questions", "Clear answers before you arrive"],
      whatsapp: ["WhatsApp", "Ask us directly"],
      book: "Request a table",
    },
    mobile: {
      aria: "Quick actions",
      whatsappAria: "Message the restaurant on WhatsApp",
      menuAria: "Open the live English menu",
      menu: "Menu",
      directionsAria: "Get directions in Google Maps",
      directions: "Directions",
    },
    hero: {
      aria: "Tarihi Van Kahvaltı Evi introduction",
      year: "Since 1978",
      place: "A family table in Beyoğlu",
      titleLineOne: "Traditional Turkish",
      titleLineTwo: "Breakfast near Taksim",
      intro: "Van herb cheese, murtuğa, kavut, hot copper pans and freshly brewed Turkish tea.",
      floatingAlts: {
        pan: "Eggs with Turkish sucuk in a copper pan",
        tea: "Fresh Turkish tea in a tulip-shaped glass",
        simit: "Warm sesame simit on a wooden board",
        omelette: "Freshly prepared breakfast omelette",
        cheese: "Selection of regional Van cheeses",
        greens: "Plate of fresh herbs and vegetables",
        olives: "Bowl of black olives",
        jam: "Bowl of homemade apricot preserve",
      },
    },
    about: {
      meta: "Our story",
      title: "A Van breakfast table,",
      titleEmphasis: "set slowly in Taksim.",
      lead:
        "On characterful Zambak Street, we bring Van's much-loved flavours to one generous table. From herb cheese and murtuğa to warm pişi and homemade preserves, everything is prepared fresh each day. For us, breakfast is not a quick meal; tea keeps coming, conversation lingers and the table is shared.",
      primaryAction: "Explore the live menu",
      bookingAction: "Request a table",
      actionsAria: "Continue from our story",
      principlesAria: "What shapes the Tarihi Van Kahvaltı Evi experience",
      tableAlt: "Friends passing cheese, preserves and tahini across a shared Van breakfast table",
      memoryAlt: "An ornate historic mirror reflecting the restaurant's brick wall",
      principles: [
        ["Walkable from Taksim", "On Zambak Street, a few steps from Taksim, İstiklal Avenue and the M2 metro."],
        ["Prepared each day", "Homemade preserves, warm pişi and a breakfast table assembled with care."],
        ["Flavours of Van", "Herb cheese, murtuğa, kete and strong Turkish tea give the table its regional character."],
      ],
    },
    gallery: {
      title: "Around",
      titleAccent: "our table",
      booking: "Request a table",
      aria: "Restaurant and breakfast gallery",
      close: "Close gallery",
      previous: "Previous photo",
      next: "Next photo",
      view: "View photo",
      images: [
        ["/images/balcony-breakfast.webp", "Van breakfast served on the balcony"],
        ["/images/sucuk-egg.webp", "Hot eggs with sucuk in a copper pan"],
        ["/images/hands-table.webp", "Friends sharing dishes across the breakfast table"],
        ["/images/interior-chair.webp", "Historic details inside the Beyoğlu restaurant"],
        ["/images/tea-service.webp", "Fresh Turkish tea served throughout breakfast"],
        ["/images/breakfast-spread.webp", "A generous traditional Van breakfast spread"],
        ["/images/historic-mirror.webp", "The restaurant's ornate historic mirror"],
        ["/images/terrace-tea.webp", "Turkish tea and breakfast on the terrace"],
        ["/images/coffee-moment.webp", "A coffee break at Kafka Cafe"],
        ["/images/street-table.webp", "Breakfast tables on Zambak Street in Beyoğlu"],
      ],
    },
    faq: {
      eyebrow: "Before you visit",
      title: "Visitor questions",
      intro: "Practical answers about our traditional Turkish breakfast near Taksim.",
      items: englishFaqItems,
    },
    footer: {
      sceneAria: "A nostalgic İstiklal Avenue tram, Galata Tower and the historic Beyoğlu skyline",
      backToTop: "Back to top",
      manifesto: "A Van breakfast,",
      manifestoEmphasis: "served with a sense of history.",
      description:
        "Our family story began in 1978. Today, the texture of a historic Beyoğlu building meets the sound of copper pans and an ever-fresh pot of Turkish tea.",
      booking: "Request a Table",
      explore: "Explore",
      exploreLinks: [
        ["/en/menu", "Live English Menu"],
        ["/en/blog/turkish-breakfast-istanbul", "Complete Turkish Breakfast Guide"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي"],
        ["/ko/blog/istanbul-bal-kaymak", "한국어 발 카이막 가이드"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語バル・カイマクガイド"],
        ["/en#story", "What Makes a Van Breakfast"],
        ["/en#story", "Our Story Since 1978"],
        ["https://www.google.com/maps?cid=10380797280962926014", "Directions from Taksim"],
        ["/en/menu#icecekler", "Tea & Kafka Cafe"],
        ["/en#faq", "Visitor Questions"],
        ["/", "Türkçe Site"],
      ],
      contact: "Contact",
      whatsapp: "Ask on WhatsApp",
      listedTitle: "Grade II",
      listedSubtitle: "Historic Building",
      hours: "Open Every Day",
      copyright: "© 2026 Tarihi Van Kahvaltı Evi. All rights reserved.",
      privacy: "Privacy policy (Turkish)",
      cookies: "Cookie policy (Turkish)",
    },
  },
} as const;

export function messagesFor(locale: SiteLocale) {
  return homeMessages[locale];
}
