import { faqItems } from "./seo";

export type SiteLocale = "tr" | "en";

export const englishFaqItems = [
  {
    question: "Where can I have a traditional Turkish breakfast near Taksim?",
    answer:
      "Tarihi Van Kahvaltı Evi serves a traditional Van-style Turkish breakfast on Zambak Street in Beyoğlu, within walking distance of Taksim Square and İstiklal Avenue.",
  },
  {
    question: "What is included in a Van breakfast?",
    answer:
      "A Van breakfast is a shared table of regional cheeses, olives, honey and clotted cream, homemade preserves, breads, hot egg dishes, murtuğa, kavut and freshly brewed Turkish tea. Availability may vary with the season and daily preparation.",
  },
  {
    question: "What are murtuğa and kavut?",
    answer:
      "Murtuğa is a warm Van speciality made with flour, butter and egg. Kavut is a rich, gently sweet dish based on toasted flour and butter. Both are traditionally served as part of the breakfast table.",
  },
  {
    question: "What time is Tarihi Van Kahvaltı Evi open?",
    answer:
      "Tarihi Van Kahvaltı Evi is open every day from 08:00 to 18:00. Please contact the restaurant before travelling on public holidays or with a large group.",
  },
  {
    question: "Where can I see the current menu and prices?",
    answer:
      "The live English menu lists the current shared breakfasts, hot dishes, regional specialities, tea and coffee prices in Turkish lira. Prices and availability can change, so check it shortly before your visit.",
  },
  {
    question: "How can I request a reservation?",
    answer:
      "Call +90 541 525 2868 or send a WhatsApp message. Your table is confirmed only after the restaurant replies.",
  },
] as const;

export const homeMessages = {
  tr: {
    documentLanguage: "tr",
    alternateLanguage: "EN",
    alternateLanguageLabel: "English",
    alternateHref: "/en",
    homeHref: "/#top",
    menuHref: "/menu",
    aboutHref: "/hikayemiz",
    galleryHref: "/#gallery",
    faqHref: "/#faq",
    nav: {
      aria: "Ana menü",
      about: "Hakkımızda",
      menu: "Menü",
      gallery: "Galeri",
      location: "Konum",
      faq: "SSS",
      open: "Menüyü aç",
      close: "Menüyü kapat",
      panelTitle: "Menü",
      home: ["Ana sayfa", "Sıcak sofra açılışı"],
      story: ["Hakkımızda", "Tarihi Rum binası"],
      liveMenu: ["Menü", "Fiyatlar ve içerik"],
      galleryItem: ["Galeri", "Bakır, çay, masa"],
      directions: ["Konum", "Beyoğlu rotası"],
      breakfast: ["Van kahvaltısı", "Yöresel lezzetler ve fiyatlar"],
      internationalGuides: [
        ["/en/blog/turkish-breakfast-istanbul", "English guide", "Traditional Turkish breakfast", "en"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид", "Турецкий завтрак в Стамбуле", "ru"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي", "الفطور التركي في إسطنبول", "ar"],
        ["/ko", "한국어 가이드", "카이막과 터키식 아침 식사", "ko"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語ガイド", "イスタンブールのバル・カイマク", "ja"],
      ],
      questions: ["Sıkça sorulanlar", "Kısa ve net cevaplar"],
      whatsapp: ["WhatsApp", "Hızlı iletişim"],
      book: "Masada yerini ayırt",
    },
    mobile: {
      aria: "Hızlı işlemler",
      whatsappAria: "WhatsApp üzerinden mesaj gönderin",
      menuAria: "QR menüyü açın",
      menu: "Menü",
      directionsAria: "Haritada yol tarifi alın",
      directions: "Yol Tarifi",
    },
    hero: {
      aria: "Tarihi Van Kahvaltı Evi ana alanı",
      year: "1978",
      yearSuffix: "’den beri",
      place: "Beyoğlu'nda bir aile sofrası",
      titleLineOne: "Tarihi",
      titleAccent: "Van",
      titleLineTwo: "Kahvaltı Evi",
      intro: "Otlu peynir, murtuğa, kavut ve bakır sahanlar. Çayımız hep taze.",
      floatingAlts: {
        pan: "Bakır sahanda sucuklu yumurta",
        tea: "İnce belli çay",
        simit: "Ahşap tabakta sıcak simit",
        omelette: "Kahvaltı tabağı",
        cheese: "Van peynir tabağı",
        greens: "Taze yeşillik tabağı",
        olives: "Siyah zeytin kasesi",
        jam: "Kayısı reçeli kasesi",
      },
    },
    about: {
      meta: "Hakkımızda",
      title: "Van sofrası,",
      titleEmphasis: "Taksim'de ağır ağır kurulur.",
      lead:
        "Zambak Sokak'ın kendine özgü dokusu içinde, Van kahvaltısının sevilen tatlarını aynı sofrada buluşturuyoruz. Otlu peynirden murtuğaya, sıcak pişiden ev yapımı reçellere kadar her tabağı günlük, taze ve özenli hazırlıyoruz. Nostaljik ayrıntılarla çevrili mekânımızda kahvaltıyı hızlı bir öğün değil; çayın demlendiği, sohbetin uzadığı sakin bir buluşma olarak görüyoruz.",
      primaryAction: "Menüyü incele",
      bookingAction: "Rezervasyon yap",
      actionsAria: "Hakkımızda bölümü sonraki adımlar",
      principlesAria: "Tarihi Van Kahvaltı Evi'nin sofra yaklaşımı",
      tableAlt: "Kahvaltı sofrasında peynir, reçel ve tahin tabaklarını uzatan eller",
      memoryAlt: "Mekândaki oymalı çerçeveli ayna ve aynaya yansıyan tuğla duvar",
      principles: [
        ["Beyoğlu konumu", "Zambak Sokak'ta; Taksim Meydanı, İstiklal Caddesi ve M2 Taksim durağına yürüme mesafesindeyiz."],
        ["Günlük emek", "Her sabah hazırlanan reçeller, sıcak pişiler ve özenle kurulan kahvaltı."],
        ["Van sofrası", "Otlu peynir, murtuğa, kete ve demli çayla kurulan yöresel sofra."],
      ],
    },
    reviews: {
      eyebrow: "Misafir notları",
      title: "Misafirlerin",
      titleAccent: "gözünden.",
      intro: "Soframızı, lezzetlerimizi ve mekânın ruhunu bu kez bizi ziyaret edenler anlatıyor.",
      googleLabel: "Google yorumları",
      rating: "4,9",
      ratingLabel: "5 üzerinden ortalama puan",
      count: "1.316 misafir değerlendirmesi",
      viewAll: "Tüm yorumları Google'da gör",
      previous: "Önceki yorumu göster",
      next: "Sonraki yorumu göster",
      choose: "Bu yorumu göster",
      photoLabel: "Mekândan bir kare",
      reviews: [
        {
          name: "Emil Qasimov",
          time: "3 saat önce",
          quote: "Her şey güzeldi, personelin samimiyetinden çok memnun kaldım. Özellikle Geni Bey’e ayrıca teşekkür ederim",
          photo: "/images/balcony-breakfast.webp",
          alt: "Tarihi binanın balkonunda kurulan Van kahvaltısı sofrası",
        },
        {
          name: "Yizheng Liang",
          time: "3 saat önce",
          quote: "Bu kahvaltı mekanı güzel, ortamı rahat.",
          photo: "/images/interior-chair.webp",
          alt: "Mekândaki nostaljik telefon, koltuk ve çiçekler",
        },
        {
          name: "Rafeek Syoufi",
          time: "3 saat önce",
          quote: "Çok güzel kahvaltı ve iyi hizmet, teşekkürler.",
          photo: "/images/breakfast-spread.webp",
          alt: "Bakır sahanlar ve yöresel peynirlerle hazırlanan Van kahvaltısı",
        },
        {
          name: "mohd almajydi",
          time: "4 saat önce",
          quote: "Yemekler çok lezzetli ve servis mükemmel, özellikle çok yardımsever ve nazik olan Bay Abdul Ghani ve Bay Abdul Samad'a teşekkür ederim.",
          photo: "/images/street-table.webp",
          alt: "Sokak cephesinde kurulan kahvaltı masası",
        },
        {
          name: "Kanyarat高蘭（高蘭AR101288）",
          time: "4 saat önce",
          quote: "Çok lezzetli!",
          photo: "/images/terrace-tea.webp",
          alt: "Terasta servis edilen çay ve kahvaltı",
        },
        {
          name: "Aithken Lakay",
          time: "5 saat önce",
          quote: "Otel kahvaltınızı unutun ve doğrudan buraya gelin!! Mekanın kendine has bir havası var ve çalışanlar gerçekten çok iyiler. Her şey son derece taze, kabarık kızarmış donutlar ve çıtır çıtır gözlemeler muhteşem. Bal ve kremalı olanı deneyin, bana tekrar tekrar söyleyeceksiniz! Bu mekan her kuruşuna değer!!",
          photo: "/images/tea-service.webp",
          alt: "Taze demlenmiş çay servisi",
        },
        {
          name: "Emine Pektaş",
          time: "22 saat önce",
          quote: "Harika🫨🩷",
          photo: "/images/hands-table.webp",
          alt: "Kahvaltı sofrasında paylaşılan yöresel tabaklar",
        },
        {
          name: "“F3” Fredrik Brostrom",
          time: "1 gün önce",
          quote: "Anahtarımla girebileceğim harika bir küçük kahve dükkanı, güler yüzlü ve yardımsever personel. Bir ipucu... ballı taze kremayı deneyin. Her zaman çok lezzetli oluyorlar!",
          photo: "/images/balcony-breakfast.webp",
          alt: "Tarihi binanın balkonunda kurulan Van kahvaltısı sofrası",
        },
        {
          name: "Zoe V",
          time: "1 gün önce",
          quote: "Burada gerçekten çok güzel vakit geçirdim ve yemekler de çok lezzetliydi 😊 İnsanlar çok iyiydi",
          photo: "/images/interior-chair.webp",
          alt: "Mekândaki nostaljik telefon, koltuk ve çiçekler",
        },
        {
          name: "L Burki",
          time: "1 gün önce",
          quote: "Öğle yemeği için harika bir yer! Anne-kız olarak harika bir öğle yemeği yedik :)",
          photo: "/images/breakfast-spread.webp",
          alt: "Bakır sahanlar ve yöresel peynirlerle hazırlanan Van kahvaltısı",
        },
        {
          name: "Nodira m",
          time: "1 gün önce",
          quote: "Taksim Meydanı ve İstiklal Caddesi'ne yakın, merkezde çok şirin bir kahvaltı kafesi. Özellikle ikinci kattaki masaları tavsiye ederim; sessiz, rahat ve yaratıcı bir atmosfere sahip.",
          photo: "/images/street-table.webp",
          alt: "Sokak cephesinde kurulan kahvaltı masası",
        },
        {
          name: "Katka Mazorova",
          time: "1 gün önce",
          quote: "Bu yeri o kadar çok sevdim ki, yemekleri ve gerçekten güzel servisi sayesinde tekrar gelmek istiyorum. Burada Türkçe dışında başka bir dil konuşan çok az insan var ve tüm çalışanlar İngilizce konuşuyor, bu da her turistin takdir edeceği bir şey. Böyle bir yer olduğu için çok mutluyum. :) Siz de ziyaret edin ve keyfini çıkarın.",
          photo: "/images/terrace-tea.webp",
          alt: "Terasta servis edilen çay ve kahvaltı",
        },
        {
          name: "bahar özkan",
          time: "1 gün önce",
          quote: "çok iyiydi gerçekten puanı çok yüksek diye şaşırmıştık genelde bu puanlarda restoran bulmak çok zor. ama her bir puanı hak ediyor. çalışanlar çok güler yüzlü nazik ve kibar. teşekkür ederiz",
          photo: "/images/tea-service.webp",
          alt: "Taze demlenmiş çay servisi",
        },
        {
          name: "Samir Askarov",
          time: "1 gün önce",
          quote: "Ortamı ve atmosferi önemseyen herkese burayı tavsiye ederim. Yemekler çok lezzetliydi ve tam kahvaltı dahil dördüncü yemeğin hesabı 2.600 ruble tuttu.",
          photo: "/images/hands-table.webp",
          alt: "Kahvaltı sofrasında paylaşılan yöresel tabaklar",
        },
        {
          name: "Zhor Elgharbaoui",
          time: "1 gün önce",
          quote: "Çok lezzetli ve servis de harika.",
          photo: "/images/balcony-breakfast.webp",
          alt: "Tarihi binanın balkonunda kurulan Van kahvaltısı sofrası",
        },
        {
          name: "hejar zeynab",
          time: "1 gün önce",
          quote: "Mükemmel servis ve kahvaltı. Garsonlar çok kibardı.",
          photo: "/images/interior-chair.webp",
          alt: "Mekândaki nostaljik telefon, koltuk ve çiçekler",
        },
        {
          name: "공수경",
          time: "1 gün önce",
          quote: "Gerçekten çok lezzetli bir yemekti. Kaymak da, menemen de çok lezzetliydi!!! Bir bardak ballı süt içmek tüm vücudumu ısıttı..!!!",
          photo: "/images/breakfast-spread.webp",
          alt: "Bakır sahanlar ve yöresel peynirlerle hazırlanan Van kahvaltısı",
        },
        {
          name: "Joaquín Rodriguez Pestana",
          time: "1 gün önce",
          quote: "Esas olarak kahvaltı için uygun; öğle yemeği için tavsiye etmem.",
          photo: "/images/street-table.webp",
          alt: "Sokak cephesinde kurulan kahvaltı masası",
        },
        {
          name: "Sara Laura Rodríguez Pestana",
          time: "1 gün önce",
          quote: "Özellikle kahvaltı için çok lezzetli yemekler 👍🏻",
          photo: "/images/terrace-tea.webp",
          alt: "Terasta servis edilen çay ve kahvaltı",
        },
        {
          name: "Delaram Ojaghian",
          time: "2 gün önce",
          quote: "Kahvaltı güzel, ortam hoş ama servis çok yavaş. Yemeklerin gelmesi için yaklaşık 40 dakika veya daha fazla bekledik.",
          photo: "/images/tea-service.webp",
          alt: "Taze demlenmiş çay servisi",
        },
      ],
    },
    gallery: {
      title: "Mekan",
      titleAccent: "anları",
      booking: "Rezervasyon al",
      aria: "Mekan fotoğrafları",
      close: "Galeri kapat",
      previous: "Önceki fotoğraf",
      next: "Sonraki fotoğraf",
      view: "Görüntüle",
      images: [
        ["/images/balcony-breakfast.webp", "Balkonda kahvaltı keyfi"],
        ["/images/sucuk-egg.webp", "Sıcak sahanda sucuklu yumurta"],
        ["/images/hands-table.webp", "Masada paylaşım anları"],
        ["/images/interior-chair.webp", "Tarihi Rum binası iç mekan dokusu"],
        ["/images/tea-service.webp", "Sınırsız taze demlenmiş çay servisi"],
        ["/images/breakfast-spread.webp", "Geleneksel serpme Van sofrası"],
        ["/images/historic-mirror.webp", "Tarihi ayna ve bina detayları"],
        ["/images/terrace-tea.webp", "Teras keyfi ve çay servisi"],
        ["/images/coffee-moment.webp", "Kafka Cafe kahve molası"],
        ["/images/street-table.webp", "Beyoğlu sokaklarında kahvaltı masası"],
      ],
    },
    faq: {
      eyebrow: "Merak edilenler",
      title: "Sıkça Sorulan Sorular",
      intro: "Tarihi Van Kahvaltı Evi ve serpme kahvaltımız hakkında kısa cevaplar.",
      items: faqItems,
    },
    footer: {
      sceneAria: "İstiklal Caddesi’nde nostaljik tramvay, Galata Kulesi ve tarihi Beyoğlu silüeti",
      backToTop: "Başa dön",
      manifesto: "Van kahvaltısı,",
      manifestoEmphasis: "tarihle aynı sofrada.",
      description:
        "1978’den beri süregelen aile yolculuğumuzda, Beyoğlu’nun kalbindeki tarihi Rum binasının dokusunu, bakır sahanların tınısı ve eksilmeyen demli çayımızla buluşturuyoruz.",
      booking: "Masada Yerini Ayırt",
      explore: "Keşfet",
      exploreLinks: [
        ["/menu", "Zengin Menü"],
        ["/van-kahvaltisi", "Van Kahvaltısı Rehberi"],
        ["/van-kahvaltisi-nedir", "Van Kahvaltısı Nedir?"],
        ["/hikayemiz", "1978'den Beri Hikâyemiz"],
        ["/konum", "Beyoğlu ve Taksim Kahvaltı"],
        ["/menu", "Kafka Cafe"],
        ["/konum", "Konum ve Yol Tarifi"],
        ["/#faq", "Sıkça Sorulan Sorular"],
        ["/en", "English Visitor Guide"],
        ["/en/blog/turkish-breakfast-istanbul", "English Breakfast Guide"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Гид на русском"],
        ["/ar/blog/turkish-breakfast-istanbul", "دليل الفطور بالعربية"],
        ["/ko", "한국어 카이막·아침 식사 가이드"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語バル・カイマクガイド"],
      ],
      contact: "Bize Ulaşın",
      whatsapp: "WhatsApp İletişim",
      listedTitle: "2. Derece",
      listedSubtitle: "Tarihi Eser",
      hours: "Her Gün Açığız",
      copyright: "© 2026 Tarihi Van Kahvaltı Evi. Tüm hakları saklıdır.",
      privacy: "Gizlilik Politikası",
      cookies: "Çerez Politikası",
    },
  },
  en: {
    documentLanguage: "en",
    alternateLanguage: "TR",
    alternateLanguageLabel: "Türkçe",
    alternateHref: "/",
    homeHref: "/en#top",
    menuHref: "/en/menu",
    aboutHref: "/en#story",
    galleryHref: "/en#gallery",
    faqHref: "/en#faq",
    nav: {
      aria: "Main navigation",
      about: "Our story",
      menu: "Menu",
      gallery: "Gallery",
      location: "Directions",
      faq: "FAQ",
      open: "Open navigation",
      close: "Close navigation",
      panelTitle: "Explore",
      home: ["Home", "A table waiting in Beyoğlu"],
      story: ["Our story", "A family breakfast house since 1978"],
      liveMenu: ["Live menu", "Current dishes and prices"],
      galleryItem: ["Gallery", "Copper pans, tea and shared tables"],
      directions: ["Directions", "Find us near Taksim"],
      breakfast: ["Van breakfast", "Meet the regional specialities"],
      internationalGuides: [
        ["/en/blog/turkish-breakfast-istanbul", "English guide", "Traditional Turkish breakfast", "en"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид", "Турецкий завтрак в Стамбуле", "ru"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي", "الفطور التركي في إسطنبول", "ar"],
        ["/ko", "한국어 가이드", "카이막과 터키식 아침 식사", "ko"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語ガイド", "イスタンブールのバル・カイマク", "ja"],
      ],
      questions: ["Visitor questions", "Clear answers before you arrive"],
      whatsapp: ["WhatsApp", "Ask us directly"],
      book: "Request a table",
    },
    mobile: {
      aria: "Quick actions",
      whatsappAria: "Message the restaurant on WhatsApp",
      menuAria: "Open the live English menu",
      menu: "Menu",
      directionsAria: "Get directions in Google Maps",
      directions: "Directions",
    },
    hero: {
      aria: "Tarihi Van Kahvaltı Evi introduction",
      year: "1978",
      yearSuffix: "Since",
      place: "A family table in Beyoğlu",
      titleLineOne: "Traditional",
      titleAccent: "Turkish",
      titleLineTwo: "Breakfast near Taksim",
      intro: "Van herb cheese, murtuğa, kavut and hot copper pans. Turkish tea, always freshly brewed.",
      floatingAlts: {
        pan: "Eggs with Turkish sucuk in a copper pan",
        tea: "Fresh Turkish tea in a tulip-shaped glass",
        simit: "Warm sesame simit on a wooden board",
        omelette: "Freshly prepared breakfast omelette",
        cheese: "Selection of regional Van cheeses",
        greens: "Plate of fresh herbs and vegetables",
        olives: "Bowl of black olives",
        jam: "Bowl of homemade apricot preserve",
      },
    },
    about: {
      meta: "Our story",
      title: "A Van breakfast table,",
      titleEmphasis: "set slowly in Taksim.",
      lead:
        "On characterful Zambak Street, we bring the much-loved flavours of Van to one generous table. From herb cheese and murtuğa to warm pişi and homemade preserves, everything is prepared fresh with daily care. Surrounded by the details of our historic Beyoğlu home, breakfast becomes more than a quick meal: tea keeps coming, conversation lingers and the table is shared.",
      primaryAction: "Explore the live menu",
      bookingAction: "Request a table",
      actionsAria: "Continue from our story",
      principlesAria: "What shapes the Tarihi Van Kahvaltı Evi experience",
      tableAlt: "Friends passing cheese, preserves and tahini across a shared Van breakfast table",
      memoryAlt: "An ornate historic mirror reflecting the restaurant's brick wall",
      principles: [
        ["Walkable from Taksim", "On Zambak Street, within walking distance of Taksim Square, İstiklal Avenue and the M2 metro."],
        ["Prepared each day", "Homemade preserves, warm pişi and a breakfast table assembled with care."],
        ["Flavours of Van", "Herb cheese, murtuğa, kete and strong Turkish tea give the table its regional character."],
      ],
    },
    reviews: {
      eyebrow: "Guest notes",
      title: "Through our",
      titleAccent: "guests' eyes.",
      intro: "This time, our guests tell the story of the table, the flavours and the character of our home.",
      googleLabel: "Google reviews",
      rating: "4.9",
      ratingLabel: "Average rating out of 5",
      count: "1,316 guest reviews",
      viewAll: "See all reviews on Google",
      previous: "Show previous review",
      next: "Show next review",
      choose: "Show this review",
      photoLabel: "A moment from the restaurant",
      reviews: [
        {
          name: "Emil Qasimov",
          time: "3 hours ago",
          quote: "Her şey güzeldi, personelin samimiyetinden çok memnun kaldım. Özellikle Geni Bey’e ayrıca teşekkür ederim",
          photo: "/images/balcony-breakfast.webp",
          alt: "A Van breakfast table set on the historic building's balcony",
        },
        {
          name: "Yizheng Liang",
          time: "3 hours ago",
          quote: "Bu kahvaltı mekanı güzel, ortamı rahat.",
          photo: "/images/interior-chair.webp",
          alt: "The restaurant's vintage telephone, armchair and flowers",
        },
        {
          name: "Rafeek Syoufi",
          time: "3 hours ago",
          quote: "Çok güzel kahvaltı ve iyi hizmet, teşekkürler.",
          photo: "/images/breakfast-spread.webp",
          alt: "A Van breakfast with copper pans and regional cheeses",
        },
        {
          name: "mohd almajydi",
          time: "4 hours ago",
          quote: "Yemekler çok lezzetli ve servis mükemmel, özellikle çok yardımsever ve nazik olan Bay Abdul Ghani ve Bay Abdul Samad'a teşekkür ederim.",
          photo: "/images/street-table.webp",
          alt: "A breakfast table set along the street frontage",
        },
        {
          name: "Kanyarat高蘭（高蘭AR101288）",
          time: "4 hours ago",
          quote: "Çok lezzetli!",
          photo: "/images/terrace-tea.webp",
          alt: "Tea and breakfast served on the terrace",
        },
        {
          name: "Aithken Lakay",
          time: "5 hours ago",
          quote: "Otel kahvaltınızı unutun ve doğrudan buraya gelin!! Mekanın kendine has bir havası var ve çalışanlar gerçekten çok iyiler. Her şey son derece taze, kabarık kızarmış donutlar ve çıtır çıtır gözlemeler muhteşem. Bal ve kremalı olanı deneyin, bana tekrar tekrar söyleyeceksiniz! Bu mekan her kuruşuna değer!!",
          photo: "/images/tea-service.webp",
          alt: "Freshly brewed Turkish tea being served",
        },
        {
          name: "Emine Pektaş",
          time: "22 hours ago",
          quote: "Harika🫨🩷",
          photo: "/images/hands-table.webp",
          alt: "Regional dishes being shared around the breakfast table",
        },
        {
          name: "“F3” Fredrik Brostrom",
          time: "1 day ago",
          quote: "Anahtarımla girebileceğim harika bir küçük kahve dükkanı, güler yüzlü ve yardımsever personel. Bir ipucu... ballı taze kremayı deneyin. Her zaman çok lezzetli oluyorlar!",
          photo: "/images/balcony-breakfast.webp",
          alt: "A Van breakfast table set on the historic building's balcony",
        },
        {
          name: "Zoe V",
          time: "1 day ago",
          quote: "I had a really good time and the food was delicious 😊 Nice people.",
          photo: "/images/interior-chair.webp",
          alt: "The restaurant's vintage telephone, armchair and flowers",
        },
        {
          name: "L Burki",
          time: "1 day ago",
          quote: "Great place for lunch! We had a wonderful mother-daughter lunch :)",
          photo: "/images/breakfast-spread.webp",
          alt: "A Van breakfast with copper pans and regional cheeses",
        },
        {
          name: "Nodira m",
          time: "1 day ago",
          quote: "Taksim Meydanı ve İstiklal Caddesi'ne yakın, merkezde çok şirin bir kahvaltı kafesi. Özellikle ikinci kattaki masaları tavsiye ederim; sessiz, rahat ve yaratıcı bir atmosfere sahip.",
          photo: "/images/street-table.webp",
          alt: "A breakfast table set along the street frontage",
        },
        {
          name: "Katka Mazorova",
          time: "1 day ago",
          quote: "Bu yeri o kadar çok sevdim ki, yemekleri ve gerçekten güzel servisi sayesinde tekrar gelmek istiyorum. Burada Türkçe dışında başka bir dil konuşan çok az insan var ve tüm çalışanlar İngilizce konuşuyor, bu da her turistin takdir edeceği bir şey. Böyle bir yer olduğu için çok mutluyum. :) Siz de ziyaret edin ve keyfini çıkarın.",
          photo: "/images/terrace-tea.webp",
          alt: "Tea and breakfast served on the terrace",
        },
        {
          name: "bahar özkan",
          time: "1 day ago",
          quote: "çok iyiydi gerçekten puanı çok yüksek diye şaşırmıştık genelde bu puanlarda restoran bulmak çok zor. ama her bir puanı hak ediyor. çalışanlar çok güler yüzlü nazik ve kibar. teşekkür ederiz",
          photo: "/images/tea-service.webp",
          alt: "Freshly brewed Turkish tea being served",
        },
        {
          name: "Samir Askarov",
          time: "1 day ago",
          quote: "Ortamı ve atmosferi önemseyen herkese burayı tavsiye ederim. Yemekler çok lezzetliydi ve tam kahvaltı dahil dördüncü yemeğin hesabı 2.600 ruble tuttu.",
          photo: "/images/hands-table.webp",
          alt: "Regional dishes being shared around the breakfast table",
        },
        {
          name: "Zhor Elgharbaoui",
          time: "1 day ago",
          quote: "Çok lezzetli ve servis de harika.",
          photo: "/images/balcony-breakfast.webp",
          alt: "A Van breakfast table set on the historic building's balcony",
        },
        {
          name: "hejar zeynab",
          time: "1 day ago",
          quote: "Mükemmel servis ve kahvaltı. Garsonlar çok kibardı.",
          photo: "/images/interior-chair.webp",
          alt: "The restaurant's vintage telephone, armchair and flowers",
        },
        {
          name: "공수경",
          time: "1 day ago",
          quote: "Gerçekten çok lezzetli bir yemekti. Kaymak da, menemen de çok lezzetliydi!!! Bir bardak ballı süt içmek tüm vücudumu ısıttı..!!!",
          photo: "/images/breakfast-spread.webp",
          alt: "A Van breakfast with copper pans and regional cheeses",
        },
        {
          name: "Joaquín Rodriguez Pestana",
          time: "1 day ago",
          quote: "Esas olarak kahvaltı için uygun; öğle yemeği için tavsiye etmem.",
          photo: "/images/street-table.webp",
          alt: "A breakfast table set along the street frontage",
        },
        {
          name: "Sara Laura Rodríguez Pestana",
          time: "1 day ago",
          quote: "Muy buena comida para un buen desayuno en especial 👍🏻",
          photo: "/images/terrace-tea.webp",
          alt: "Tea and breakfast served on the terrace",
        },
        {
          name: "Delaram Ojaghian",
          time: "2 days ago",
          quote: "Kahvaltı güzel, ortam hoş ama servis çok yavaş. Yemeklerin gelmesi için yaklaşık 40 dakika veya daha fazla bekledik.",
          photo: "/images/tea-service.webp",
          alt: "Freshly brewed Turkish tea being served",
        },
      ],
    },
    gallery: {
      title: "Around",
      titleAccent: "our table",
      booking: "Request a table",
      aria: "Restaurant and breakfast gallery",
      close: "Close gallery",
      previous: "Previous photo",
      next: "Next photo",
      view: "View photo",
      images: [
        ["/images/balcony-breakfast.webp", "Van breakfast served on the balcony"],
        ["/images/sucuk-egg.webp", "Hot eggs with sucuk in a copper pan"],
        ["/images/hands-table.webp", "Friends sharing dishes across the breakfast table"],
        ["/images/interior-chair.webp", "Historic details inside the Beyoğlu restaurant"],
        ["/images/tea-service.webp", "Fresh Turkish tea served throughout breakfast"],
        ["/images/breakfast-spread.webp", "A generous traditional Van breakfast spread"],
        ["/images/historic-mirror.webp", "The restaurant's ornate historic mirror"],
        ["/images/terrace-tea.webp", "Turkish tea and breakfast on the terrace"],
        ["/images/coffee-moment.webp", "A coffee break at Kafka Cafe"],
        ["/images/street-table.webp", "Breakfast tables on Zambak Street in Beyoğlu"],
      ],
    },
    faq: {
      eyebrow: "Before you visit",
      title: "Visitor questions",
      intro: "Practical answers about our traditional Turkish breakfast near Taksim.",
      items: englishFaqItems,
    },
    footer: {
      sceneAria: "A nostalgic İstiklal Avenue tram, Galata Tower and the historic Beyoğlu skyline",
      backToTop: "Back to top",
      manifesto: "A Van breakfast,",
      manifestoEmphasis: "served with a sense of history.",
      description:
        "Our family story began in 1978. Today, the texture of a historic Beyoğlu building meets the sound of copper pans and an ever-fresh pot of Turkish tea.",
      booking: "Request a Table",
      explore: "Explore",
      exploreLinks: [
        ["/en/menu", "Live English Menu"],
        ["/en/blog/turkish-breakfast-istanbul", "Complete Turkish Breakfast Guide"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي"],
        ["/ko", "한국어 카이막·아침 식사 가이드"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語バル・カイマクガイド"],
        ["/en#story", "What Makes a Van Breakfast"],
        ["/en#story", "Our Story Since 1978"],
        ["https://www.google.com/maps?cid=10380797280962926014", "Directions from Taksim"],
        ["/en/menu#icecekler", "Tea & Kafka Cafe"],
        ["/en#faq", "Visitor Questions"],
        ["/", "Türkçe Site"],
      ],
      contact: "Contact",
      whatsapp: "Ask on WhatsApp",
      listedTitle: "Grade II",
      listedSubtitle: "Historic Building",
      hours: "Open Every Day",
      copyright: "© 2026 Tarihi Van Kahvaltı Evi. All rights reserved.",
      privacy: "Privacy policy (Turkish)",
      cookies: "Cookie policy (Turkish)",
    },
  },
} as const;

export function messagesFor(locale: SiteLocale) {
  return homeMessages[locale];
}
