import { faqItems } from "./seo";

export type SiteLocale = "tr" | "en";

export const englishFaqItems = [
  {
    question: "Where can I have a traditional Turkish breakfast near Taksim?",
    answer:
      "Tarihi Van Kahvaltı Evi serves a traditional Van-style Turkish breakfast on Zambak Street in Beyoğlu, within walking distance of Taksim Square and İstiklal Avenue.",
  },
  {
    question: "What is included in a Van breakfast?",
    answer:
      "A Van breakfast is a shared table of regional cheeses, olives, honey and clotted cream, homemade preserves, breads, hot egg dishes, murtuğa, kavut and freshly brewed Turkish tea. Availability may vary with the season and daily preparation.",
  },
  {
    question: "What are murtuğa and kavut?",
    answer:
      "Murtuğa is a warm Van speciality made with flour, butter and egg. Kavut is a rich, gently sweet dish based on toasted flour and butter. Both are traditionally served as part of the breakfast table.",
  },
  {
    question: "What time is Tarihi Van Kahvaltı Evi open?",
    answer:
      "Tarihi Van Kahvaltı Evi is open every day from 07:00 to 22:00. Please contact the restaurant before travelling on public holidays or with a large group.",
  },
  {
    question: "Where can I see the current menu and prices?",
    answer:
      "The live English menu lists the current shared breakfasts, hot dishes, regional specialities, tea and coffee prices in Turkish lira. Prices and availability can change, so check it shortly before your visit.",
  },
  {
    question: "How can I request a reservation?",
    answer:
      "Call +90 541 525 2868 or send a WhatsApp message. Your table is confirmed only after the restaurant replies.",
  },
] as const;

export const homeMessages = {
  tr: {
    documentLanguage: "tr",
    alternateLanguage: "EN",
    alternateLanguageLabel: "English",
    alternateHref: "/en",
    homeHref: "/#top",
    reservationHref: "/rezervasyon",
    menuHref: "/menu",
    aboutHref: "/hikayemiz",
    galleryHref: "/#gallery",
    faqHref: "/#faq",
    nav: {
      aria: "Ana menü",
      about: "Hakkımızda",
      menu: "Menü",
      gallery: "Galeri",
      location: "Konum",
      faq: "SSS",
      open: "Menüyü aç",
      close: "Menüyü kapat",
      panelTitle: "Menü",
      home: ["Ana sayfa", "Sıcak sofra açılışı"],
      story: ["Hakkımızda", "Tarihi Rum binası"],
      liveMenu: ["Menü", "Fiyatlar ve içerik"],
      galleryItem: ["Galeri", "Bakır, çay, masa"],
      directions: ["Konum", "Beyoğlu rotası"],
      breakfast: ["Van kahvaltısı", "Yöresel lezzetler ve fiyatlar"],
      internationalGuides: [
        ["/en/blog/turkish-breakfast-istanbul", "English guide", "Traditional Turkish breakfast", "en"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид", "Турецкий завтрак в Стамбуле", "ru"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي", "الفطور التركي في إسطنبول", "ar"],
        ["/ko", "한국어 가이드", "카이막과 터키식 아침 식사", "ko"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語ガイド", "イスタンブールのバル・カイマク", "ja"],
      ],
      questions: ["Sıkça sorulanlar", "Kısa ve net cevaplar"],
      whatsapp: ["WhatsApp", "Hızlı iletişim"],
      book: "Masada yerini ayırt",
    },
    mobile: {
      aria: "Hızlı işlemler",
      whatsappAria: "WhatsApp üzerinden mesaj gönderin",
      menuAria: "QR menüyü açın",
      menu: "Menü",
      directionsAria: "Haritada yol tarifi alın",
      directions: "Yol Tarifi",
    },
    hero: {
      aria: "Tarihi Van Kahvaltı Evi ana alanı",
      year: "1978",
      yearSuffix: "’den beri",
      place: "Beyoğlu'nda bir aile sofrası",
      titleLineOne: "Tarihi",
      titleAccent: "Van",
      titleLineTwo: "Kahvaltı Evi",
      intro: "Otlu peynir, murtuğa, kavut ve bakır sahanlar. Çayımız hep taze.",
      floatingAlts: {
        pan: "Bakır sahanda sucuklu yumurta",
        tea: "İnce belli çay",
        simit: "Ahşap tabakta sıcak simit",
        omelette: "Kahvaltı tabağı",
        cheese: "Van peynir tabağı",
        greens: "Taze yeşillik tabağı",
        olives: "Siyah zeytin kasesi",
        jam: "Kayısı reçeli kasesi",
      },
    },
    about: {
      meta: "Hikâyemiz & Değerlerimiz",
      crestAlt: "Tarihi Van Kahvaltı Evi Arması",
      eyebrow: "1978'den Bugüne Aile Geleneği",
      title: "Van Sofrası,",
      titleEmphasis: "Taksim'de Ağır Ağır Kurulur.",
      lead:
        "Zambak Sokak'ın kendine özgü tarihi dokusu içinde, Van kahvaltısının asırlık lezzetlerini aynı masada buluşturuyoruz. Van yaylalarının kekik kokulu otlarıyla mayalanan hakiki otlu peyniri, taş fırından yeni çıkmış çıtır pişisi, odun ateşinde demlenen semaver çayı ve bakır sahanda tereyağıyla cızırdayan kavurmalı yumurtasıyla güne unutulmaz bir başlangıç sunuyoruz.",
      storyP1:
        "Bizim için kahvaltı aceleye getirilecek sıradan bir öğün değil; taze demlenmiş tavşan kanı çayın bardak bardak doldurulduğu, bakır sahanların tınısıyla neşelenen, sevdiklerinizle saatlerce süren sıcak bir buluşma sofrasıdır.",
      storyP2:
        "Beyoğlu'nun 2. Derece Tarihi Eser tescilli yüksek tavanlı Rum konağında, nostaljik oymalı aynalar ve ahşap dokular arasında, 1978'den bu yana aynı özen, sevgi ve zanaatkar titizlikle hizmet veriyoruz.",
      primaryAction: "Hikâyemizi Keşfedin",
      secondaryAction: "Menüyü İncele",
      bookingAction: "Rezervasyon Yap",
      actionsAria: "Hakkımızda bölümü sonraki adımlar",
      principlesAria: "Tarihi Van Kahvaltı Evi'nin sofra yaklaşımı",
      tableAlt: "Kahvaltı sofrasında peynir, reçel ve tahin tabaklarını uzatan eller",
      memoryAlt: "Mekândaki oymalı çerçeveli ayna ve aynaya yansıyan tuğla duvar",
      principles: [
        ["Beyoğlu Zambak Sokak", "Taksim Meydanı ve İstiklal Caddesi'ne 2 dakika yürüme mesafesinde, tarihi Rum binasındayız."],
        ["Günlük Taş Fırın & Pişi", "Her sabah fırından yeni çıkan sıcak pişiler, Van ketesi ve anne usulü ev reçelleri."],
        ["Hakiki Yayla Lezzeti", "Doğu'nun yüksek yaylalarından getirilen otlu peynir, murtuğa, kavut ve Karakovan balı."],
      ],
    },
    atmosphere: {
      anchorAlt: "Zarif Kemer Motifi",
      locationBadge: "BEYOĞLU • İSTİKLAL • TAKSİM",
      words: ["Gelenek", "ve", "Lezzet", "Beyoğlu'nda", "Buluşuyor!"],
      lead: "Tarihi Rum konağının asırlık taş duvarları arasında, Doğu'nun en cömert kahvaltı mirası sizi bekliyor.",
      subtext: "Bakır sahanların tınısı, sınırsız demli çay ve dost sohbetleri.",
    },
    showcase: {
      eyebrow: "Zanaat & Lezzet",
      title: "İmza Van",
      titleAccent: "Lezzetlerimiz",
      lead: "Usta ellerde hazırlanan sıcak sahanlar, taş fırın hamur işleri ve yüksek yaylalardan gelen doğal lezzetler.",
      viewMenuAction: "Menüyü Keşfet",
      tableBookingAction: "Masa Ayırt",
      tabs: [
        {
          id: "serpme",
          label: "Serpme Van Sofrası",
          icon: "/images/menu-category-icons/breakfast.png",
          heading: "Zengin Serpme Van Kahvaltısı",
          subtitle: "Güne Cömert ve Eksiksiz Bir Başlangıç",
          description: "Hakiki Van otlu peyniri, Karakovan petek ve süzme balı, taze manda kaymağı, murtuğa, kavut, cevizli acuka, ev yapımı meyve reçelleri, sıcacık pişiler ve semaverden sınırsız çay ile donatılmış rüya gibi bir sofra.",
          image: "/images/breakfast-spread.webp",
          badge: "İmza Sofra",
          tag: "Sınırsız Çay Dahil",
        },
        {
          id: "sahanlar",
          label: "Bakır Sahan & Sıcaklar",
          icon: "/images/menu-category-icons/pan.png",
          heading: "Ateşte Cızırdayan Bakır Sahanlar",
          subtitle: "Hakiki Köy Tereyağı ile Hazırlanan Sıcaklar",
          description: "Özel baharatlı kasap sucuklu yumurta, lokum gibi sahanda kavurma, Trabzon tereyağı ve uzayan kolot peyniriyle hazırlanan kuymak ve sulu köy domatesleriyle pişen nefis menemen.",
          image: "/images/hero-parallax/sucuk-egg-action.webp",
          badge: "Bakır Sahan",
          tag: "Taze Sıcak Servis",
        },
        {
          id: "yoresel",
          label: "Yöresel Van Tatları",
          icon: "/images/menu-category-icons/van.png",
          heading: "Kadim Van Mutfağı: Murtuğa & Kavut",
          subtitle: "Asırlık Anadolu Kahvaltı Mirası",
          description: "Kavrulmuş un, köy tereyağı ve yumurtanın muazzam uyumu murtuğa; kavrulmuş buğday ununun balla harmanlandığı enerjik kavut ve yabani dağ otlarıyla küplerde dinlendirilen meşhur otlu peynir.",
          image: "/images/menu-products/tereyagli-cevizli-murtuga.webp",
          badge: "Geleneksel Reçete",
          tag: "Van Yaylalarından",
        },
        {
          id: "balkaymak",
          label: "Bal, Kaymak & Reçeller",
          icon: "/images/menu-category-icons/jam.png",
          heading: "Yüksek Yayla Karakovan Balı & Manda Kaymağı",
          subtitle: "Doğallığın ve Saflığın Zirvesi",
          description: "Rakımı yüksek Van yaylalarının çiçeklerinden derlenen şifalı Karakovan balı, günlük taze çekilen yoğun manda kaymağı ve mevsiminde toplanmış meyvelerden anne usulü pişirilen katkısız ev reçelleri.",
          image: "/images/menu-products/bal-kaymak.webp",
          badge: "Doğal & Katkısız",
          tag: "Günlük Taze",
        },
        {
          id: "firindan",
          label: "Taş Fırın & Sıcak Pişi",
          icon: "/images/menu-category-icons/breakfast.png",
          heading: "Fırından Yeni Çıkmış Çıtır Pişi & Kete",
          subtitle: "Mis Kokulu Hamur İşleri",
          description: "Altın sarısı rengiyle hafif ve çıtır çıtır kabaran sıcak pişi sepetleri, tereyağlı iç harcıyla damakta eriyen geleneksel Van ketesi ve fırından sıcacık çıkan taze ekmekler.",
          image: "/images/menu-products/pisi-tabagi.webp",
          badge: "Taş Fırın",
          tag: "Sıcacık Sepette",
        },
        {
          id: "icecekler",
          label: "Semaver Çayı & Kahve",
          icon: "/images/menu-category-icons/hot-drink.png",
          heading: "Tavşan Kanı Semaver Çayı & Türk Kahvesi",
          subtitle: "Sohbeti Uzatan İkramlar",
          description: "Özel Karadeniz harmanıyla bakır semaverde demlenen, berrak ve tavşan kanı sınırsız çay servisi. Kahvaltı keyfini taçlandıran bol köpüklü közde Türk kahvesi ve taze sıkılmış meyve suları.",
          image: "/images/coffee-moment.webp",
          badge: "Sınırsız İkram",
          tag: "Hep Taze & Sıcak",
        },
      ],
    },
    venue: {
      badge: "2. Derece Tescilli Tarihi Eser",
      title: "Keyif Dolu Anlar Sizi Bekliyor!",
      subtitle: "Beyoğlu’nun büyüleyici tarihi atmosferi zengin Van lezzetleriyle birleşiyor.",
      description:
        "Tarihi Van Kahvaltı Evi, Doğu'nun misafirperver sofra zenginliğini Beyoğlu'nun kalbindeki tarihi Rum binasında iftiharla sunuyor. Yüksek tavanlar, nostaljik oymalı aynalar ve Zambak Sokak'ın kendine has dokusunda, keyif dolu saatler geçirmek için sizleri soframıza bekliyoruz!",
      callAction: "Bizi Arayın",
      menuAction: "Menüyü İncele",
      reservationAction: "Masa Rezervasyonu",
    },
    reviews: {
      eyebrow: "Misafir notları",
      title: "Misafirlerin",
      titleAccent: "gözünden.",
      intro: "Soframızı, lezzetlerimizi ve mekânın ruhunu bu kez bizi ziyaret edenler anlatıyor.",
      googleLabel: "Google yorumları",
      rating: "4,9",
      ratingLabel: "5 üzerinden ortalama puan",
      count: "1.316 misafir değerlendirmesi",
      viewAll: "Tüm yorumları Google'da gör",
      previous: "Önceki yorumu göster",
      next: "Sonraki yorumu göster",
      choose: "Bu yorumu göster",
      photoLabel: "Mekândan bir kare",
      reviews: [
        {
          name: "AZRA KAPKAÇ",
          time: "6 gün önce",
          quote: "Kesinlikle 5 yıldızı hak eden bir mekan! Her şey çok taze, lezzetli ve özenle hazırlanmıştı. Çeşit bolluğu ve ürünlerin kalitesi tek kelimeyle harikaydı. Ayrıca çalışanların güler yüzlü ve hızlı hizmeti de ortamın sıcaklığını iki katına çıkartıyorrr. Güne mutlu ve enerjik başlamak için bundan daha iyi bir adres olamaz. Gönül rahatlığıyla tavsiye ediyorum",
          photo: "/images/interior-chair.webp",
          alt: "Mekândaki nostaljik telefon, koltuk ve çiçekler",
        },
        {
          name: "Emine Pektaş",
          time: "22 saat önce",
          quote: "Harika🫨🩷",
          photo: "/images/balcony-breakfast.webp",
          alt: "Tarihi binanın balkonunda kurulan Van kahvaltısı sofrası",
        },
        {
          name: "bahar özkan",
          time: "1 gün önce",
          quote: "çok iyiydi gerçekten puanı çok yüksek diye şaşırmıştık genelde bu puanlarda restoran bulmak çok zor. ama her bir puanı hak ediyor. çalışanlar çok güler yüzlü nazik ve kibar. teşekkür ederiz",
          photo: "/images/interior-chair.webp",
          alt: "Mekândaki nostaljik telefon, koltuk ve çiçekler",
        },
        {
          name: "Ezgi Asikoglu",
          time: "5 gün önce",
          quote: "Her şey çok güzeldi. Güleryüzlü nazik insanlar. Keyifli vakit geçirdik",
          photo: "/images/breakfast-spread.webp",
          alt: "Bakır sahanlar ve yöresel peynirlerle hazırlanan Van kahvaltısı",
        },
        {
          name: "Zeynep Kadirağagil",
          time: "5 gün önce",
          quote: "güzeldi teşekkürler",
          photo: "/images/street-table.webp",
          alt: "Sokak cephesinde kurulan kahvaltı masası",
        },
        {
          name: "Muaz Maciter",
          time: "6 gün önce",
          quote: "Ahmet kardeşimize hizmetinden ötürü teşekkür ederiz…",
          photo: "/images/terrace-tea.webp",
          alt: "Terasta servis edilen çay ve kahvaltı",
        },
        {
          name: "Metehan Çelik",
          time: "6 gün önce",
          quote: "Yemekler ve hizmet çok iyiydi. Kesinlikle tavsiye ederim. Bizimle ilgilenen Ahmet kardeşime ilgisinden dolayı teşekkür ederim.",
          photo: "/images/tea-service.webp",
          alt: "Taze demlenmiş çay servisi",
        },
        {
          name: "Metehan",
          time: "6 gün önce",
          quote: "Ahmet bizimle çok iyi ilgilendi. Her şey çok iyiydi.",
          photo: "/images/hands-table.webp",
          alt: "Kahvaltı sofrasında paylaşılan yöresel tabaklar",
        },
        {
          name: "Hamza Maciter",
          time: "6 gün önce",
          quote: "Ahmet beye çok teşekkür ederiz her şey süperdi",
          photo: "/images/balcony-breakfast.webp",
          alt: "Tarihi binanın balkonunda kurulan Van kahvaltısı sofrası",
        },
        {
          name: "mirza ayhan",
          time: "6 gün önce",
          quote: "Mükemmel kahvaltı her şey taze hizmet mükemmel Ahmet kardeşimize alakasından dolayı teşekkür ederiz.",
          photo: "/images/interior-chair.webp",
          alt: "Mekândaki nostaljik telefon, koltuk ve çiçekler",
        },
        {
          name: "hilal yavuz",
          time: "6 gün önce",
          quote: "çok teşekkürler",
          photo: "/images/breakfast-spread.webp",
          alt: "Bakır sahanlar ve yöresel peynirlerle hazırlanan Van kahvaltısı",
        },
        {
          name: "Tulay Durmaz",
          time: "6 gün önce",
          quote: "Guzel kahvalti samet bey tatli dilli hizmetliydi guzel devam",
          photo: "/images/street-table.webp",
          alt: "Sokak cephesinde kurulan kahvaltı masası",
        },
        {
          name: "Ömer",
          time: "6 gün önce",
          quote: "Ferdi beye bizimle ilgilendiği için teşekkür ederiz her yolumuz düştüğünde uğrayacağız❤️❤️❤️",
          photo: "/images/terrace-tea.webp",
          alt: "Terasta servis edilen çay ve kahvaltı",
        },
        {
          name: "Emrah Güneysu",
          time: "6 gün önce",
          quote: "Kahvaltı çok güzeldi. Ferdi bey bizimle çok iyi ilgilendi. Tekrar yolumuz düşerse kesinlikle uğranması gereken bir yer",
          photo: "/images/tea-service.webp",
          alt: "Taze demlenmiş çay servisi",
        },
        {
          name: "Hüseyin Memiş",
          time: "6 gün önce",
          quote: "Ferdi bey teşekkür  ederim bizimle baya ilgilendi kahvaltı gerçekten çok güzeldi",
          photo: "/images/hands-table.webp",
          alt: "Kahvaltı sofrasında paylaşılan yöresel tabaklar",
        },
        {
          name: "Ahmet egüz",
          time: "6 gün önce",
          quote: "Kahvaltısı harikaydı herkese öneririm  Ferdi beye teşekkür ederiz",
          photo: "/images/balcony-breakfast.webp",
          alt: "Tarihi binanın balkonunda kurulan Van kahvaltısı sofrası",
        },
        {
          name: "Duygu Dogan",
          time: "6 gün önce",
          quote: "Kahvaltı süper tekrar teşekkürler 👍🏼",
          photo: "/images/breakfast-spread.webp",
          alt: "Bakır sahanlar ve yöresel peynirlerle hazırlanan Van kahvaltısı",
        },
        {
          name: "Serpil İlhan",
          time: "1 hafta önce",
          quote: "Çok iyi hizmet.",
          photo: "/images/street-table.webp",
          alt: "Sokak cephesinde kurulan kahvaltı masası",
        },
        {
          name: "Ayşe Akın",
          time: "1 hafta önce",
          quote: "Ailecek,Akrabalarınızla ve Arkadaşlarınızla gelebileceğiniz harika bir yer..Biz geldik ve çok beğendik atmosfer olsun yemeklerin tadı olsun herşey harikaydı....",
          photo: "/images/terrace-tea.webp",
          alt: "Terasta servis edilen çay ve kahvaltı",
        },
        {
          name: "Zekiye Deniz",
          time: "1 hafta önce",
          quote: "Herşey cok güzeldi ilgi alaka mükemmledi ellerinize sağlık",
          photo: "/images/tea-service.webp",
          alt: "Taze demlenmiş çay servisi",
        },
      ],
    },
    gallery: {
      title: "Mekan",
      titleAccent: "anları",
      booking: "Rezervasyon al",
      aria: "Mekan fotoğrafları",
      close: "Galeri kapat",
      previous: "Önceki fotoğraf",
      next: "Sonraki fotoğraf",
      view: "Görüntüle",
      images: [
        ["/images/balcony-breakfast.webp", "Balkonda kahvaltı keyfi"],
        ["/images/sucuk-egg.webp", "Sıcak sahanda sucuklu yumurta"],
        ["/images/hands-table.webp", "Masada paylaşım anları"],
        ["/images/interior-chair.webp", "Tarihi Rum binası iç mekan dokusu"],
        ["/images/tea-service.webp", "Sınırsız taze demlenmiş çay servisi"],
        ["/images/breakfast-spread.webp", "Geleneksel serpme Van sofrası"],
        ["/images/historic-mirror.webp", "Tarihi ayna ve bina detayları"],
        ["/images/terrace-tea.webp", "Teras keyfi ve çay servisi"],
        ["/images/coffee-moment.webp", "Kafka Cafe kahve molası"],
        ["/images/street-table.webp", "Beyoğlu sokaklarında kahvaltı masası"],
      ],
    },
    faq: {
      eyebrow: "Merak edilenler",
      title: "Sıkça Sorulan Sorular",
      intro: "Tarihi Van Kahvaltı Evi ve serpme kahvaltımız hakkında kısa cevaplar.",
      items: faqItems,
    },
    footer: {
      sceneAria: "İstiklal Caddesi’nde nostaljik tramvay, Galata Kulesi ve tarihi Beyoğlu silüeti",
      backToTop: "Başa dön",
      manifesto: "Van kahvaltısı,",
      manifestoEmphasis: "tarihle aynı sofrada.",
      description:
        "1978’den beri süregelen aile yolculuğumuzda, Beyoğlu’nun kalbindeki tarihi Rum binasının dokusunu, bakır sahanların tınısı ve eksilmeyen demli çayımızla buluşturuyoruz.",
      booking: "Masada Yerini Ayırt",
      explore: "Keşfet",
      exploreLinks: [
        ["/rezervasyon", "Masa Rezervasyonu"],
        ["/menu", "Zengin Menü"],
        ["/van-kahvaltisi", "Van Kahvaltısı Rehberi"],
        ["/van-kahvaltisi-nedir", "Van Kahvaltısı Nedir?"],
        ["/hikayemiz", "1978'den Beri Hikâyemiz"],
        ["/konum", "Beyoğlu ve Taksim Kahvaltı"],
        ["/menu", "Kafka Cafe"],
        ["/konum", "Konum ve Yol Tarifi"],
        ["/#faq", "Sıkça Sorulan Sorular"],
        ["/en", "English Visitor Guide"],
        ["/en/blog/turkish-breakfast-istanbul", "English Breakfast Guide"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Гид на русском"],
        ["/ar/blog/turkish-breakfast-istanbul", "دليل الفطور بالعربية"],
        ["/ko", "한국어 카이막·아침 식사 가이드"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語バル・カイマクガイド"],
      ],
      contact: "Bize Ulaşın",
      whatsapp: "WhatsApp İletişim",
      listedTitle: "2. Derece",
      listedSubtitle: "Tarihi Eser",
      hours: "Her Gün Açığız",
      copyright: "© 2026 Tarihi Van Kahvaltı Evi. Tüm hakları saklıdır.",
      privacy: "Gizlilik Politikası",
      cookies: "Çerez Politikası",
    },
  },
  en: {
    documentLanguage: "en",
    alternateLanguage: "TR",
    alternateLanguageLabel: "Türkçe",
    alternateHref: "/",
    homeHref: "/en#top",
    reservationHref: "/en/rezervasyon",
    menuHref: "/en/menu",
    aboutHref: "/en#story",
    galleryHref: "/en#gallery",
    faqHref: "/en#faq",
    nav: {
      aria: "Main navigation",
      about: "Our story",
      menu: "Menu",
      gallery: "Gallery",
      location: "Directions",
      faq: "FAQ",
      open: "Open navigation",
      close: "Close navigation",
      panelTitle: "Explore",
      home: ["Home", "A table waiting in Beyoğlu"],
      story: ["Our story", "A family breakfast house since 1978"],
      liveMenu: ["Live menu", "Current dishes and prices"],
      galleryItem: ["Gallery", "Copper pans, tea and shared tables"],
      directions: ["Directions", "Find us near Taksim"],
      breakfast: ["Van breakfast", "Meet the regional specialities"],
      internationalGuides: [
        ["/en/blog/turkish-breakfast-istanbul", "English guide", "Traditional Turkish breakfast", "en"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид", "Турецкий завтрак в Стамбуле", "ru"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي", "الفطور التركي في إسطنبول", "ar"],
        ["/ko", "한국어 가이드", "카이막과 터키식 아침 식사", "ko"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語ガイド", "イスタンブールのバル・カイマク", "ja"],
      ],
      questions: ["Visitor questions", "Clear answers before you arrive"],
      whatsapp: ["WhatsApp", "Ask us directly"],
      book: "Request a table",
    },
    mobile: {
      aria: "Quick actions",
      whatsappAria: "Message the restaurant on WhatsApp",
      menuAria: "Open the live English menu",
      menu: "Menu",
      directionsAria: "Get directions in Google Maps",
      directions: "Directions",
    },
    hero: {
      aria: "Tarihi Van Kahvaltı Evi introduction",
      year: "1978",
      yearSuffix: "Since",
      place: "A family table in Beyoğlu",
      titleLineOne: "Traditional",
      titleAccent: "Turkish",
      titleLineTwo: "Breakfast near Taksim",
      intro: "Van herb cheese, murtuğa, kavut and hot copper pans. Turkish tea, always freshly brewed.",
      floatingAlts: {
        pan: "Eggs with Turkish sucuk in a copper pan",
        tea: "Fresh Turkish tea in a tulip-shaped glass",
        simit: "Warm sesame simit on a wooden board",
        omelette: "Freshly prepared breakfast omelette",
        cheese: "Selection of regional Van cheeses",
        greens: "Plate of fresh herbs and vegetables",
        olives: "Bowl of black olives",
        jam: "Bowl of homemade apricot preserve",
      },
    },
    about: {
      meta: "Our Story & Values",
      crestAlt: "Tarihi Van Kahvaltı Evi Emblem",
      eyebrow: "A Family Tradition Since 1978",
      title: "A Van Breakfast Table,",
      titleEmphasis: "Set Slowly in Taksim.",
      lead:
        "Within the historic ambiance of Zambak Street, we bring the centuries-old breakfast traditions of Van to one shared table. From authentic wild herb cheese to oven-fresh golden pişi, steaming samovar tea and hot copper pans sizzling with eggs and butter, we offer an unforgettable start to your day.",
      storyP1:
        "To us, breakfast is not a rushed routine; it is a ritual where freshly brewed tea is poured glass after glass, copper pans sing over gentle flames, and joyful conversations stretch on for hours.",
      storyP2:
        "In our registered 2nd-degree historic Greek mansion with high ceilings, ornate antique mirrors, and authentic brickwork, our family has been serving with the same dedication, warmth, and artisanal craft since 1978.",
      primaryAction: "Discover Our Heritage",
      secondaryAction: "Explore the Live Menu",
      bookingAction: "Request a Table",
      actionsAria: "Continue from our story",
      principlesAria: "What shapes the Tarihi Van Kahvaltı Evi experience",
      tableAlt: "Friends passing cheese, preserves and tahini across a shared Van breakfast table",
      memoryAlt: "An ornate historic mirror reflecting the restaurant's brick wall",
      principles: [
        ["Beyoğlu Zambak Street", "2 minutes walk from Taksim Square and İstiklal Avenue, inside an authentic historic mansion."],
        ["Stone Oven & Fresh Pişi", "Every morning: hot golden pişi, traditional Van kete pastry, and homemade fruit preserves."],
        ["Authentic Highland Flavors", "Pure Van herb cheese, murtuğa, roasted grain kavut, and organic Karakovan honey."],
      ],
    },
    atmosphere: {
      anchorAlt: "Graceful Arch Motif",
      locationBadge: "BEYOĞLU • İSTİKLAL • TAKSİM",
      words: ["Heritage", "and", "Flavor", "Meet in", "Beyoğlu!"],
      lead: "Between the centuries-old stone walls of our historic Greek mansion, Anatolia's most generous breakfast heritage awaits you.",
      subtext: "The melody of copper pans, endless freshly brewed tea, and warm gatherings.",
    },
    showcase: {
      eyebrow: "Craft & Flavor",
      title: "Our Signature",
      titleAccent: "Van Feasts",
      lead: "Sizzling copper pans, stone-oven pastries, and all-natural treasures from high Anatolian plateaus.",
      viewMenuAction: "View Menu & Prices",
      tableBookingAction: "Reserve a Table",
      tabs: [
        {
          id: "serpme",
          label: "Grand Van Feast",
          icon: "/images/menu-category-icons/breakfast.png",
          heading: "Grand Traditional Van Spread",
          subtitle: "A Generous and Complete Morning Feast",
          description: "Real Van herb cheese, wild Karakovan honey, fresh buffalo clotted cream, murtuğa, kavut, walnut acuka, homemade preserves, hot pişi, and bottomless tea brewed in a traditional copper samovar.",
          image: "/images/breakfast-spread.webp",
          badge: "Signature Feast",
          tag: "Includes Endless Tea",
        },
        {
          id: "sahanlar",
          label: "Copper Pans & Hot Dishes",
          icon: "/images/menu-category-icons/pan.png",
          heading: "Sizzling Hot Copper Pan Specialties",
          subtitle: "Cooked with Pure Village Butter",
          description: "Spiced Turkish sucuk with farm-fresh eggs, slow-cooked braised beef kavurma, rich Trabzon kuymak with string cheese, and juicy pan-cooked Menemen.",
          image: "/images/hero-parallax/sucuk-egg-action.webp",
          badge: "Copper Pan",
          tag: "Served Sizzling Hot",
        },
        {
          id: "yoresel",
          label: "Highland Delicacies",
          icon: "/images/menu-category-icons/van.png",
          heading: "Ancient Van Kitchen: Murtuğa & Kavut",
          subtitle: "Centuries-Old Anatolian Heritage",
          description: "Murtuğa, made with slow-toasted flour, rich butter, and egg; roasted wheat flour kavut served with honey; and legendary cheese aged in earthenware jars with wild mountain herbs.",
          image: "/images/menu-products/tereyagli-cevizli-murtuga.webp",
          badge: "Heritage Recipe",
          tag: "From Van Plateaus",
        },
        {
          id: "balkaymak",
          label: "Honey & Clotted Cream",
          icon: "/images/menu-category-icons/jam.png",
          heading: "High-Altitude Karakovan Honey & Buffalo Kaymak",
          subtitle: "The Peak of Purity and Nature",
          description: "Raw comb and strained honey collected from high-altitude wildflowers, velvety daily buffalo clotted cream, and additive-free fruit jams simmered slowly over wood fire.",
          image: "/images/menu-products/bal-kaymak.webp",
          badge: "Pure & Organic",
          tag: "Daily Fresh",
        },
        {
          id: "firindan",
          label: "Bakery & Hot Pişi",
          icon: "/images/menu-category-icons/breakfast.png",
          heading: "Stone-Oven Puffed Pişi & Traditional Kete",
          subtitle: "Irresistible Warm Pastries",
          description: "Golden, crisp, airy fried pişi dough served hot in baskets, flaky butter-filled traditional Van kete, and fresh crusty artisan bread straight from our stone oven.",
          image: "/images/menu-products/pisi-tabagi.webp",
          badge: "Stone Oven",
          tag: "Basket Fresh",
        },
        {
          id: "icecekler",
          label: "Samovar Tea & Coffee",
          icon: "/images/menu-category-icons/hot-drink.png",
          heading: "Endless Samovar Tea & Turkish Coffee",
          subtitle: "Warm Refreshments That Extend Conversation",
          description: "Bottomless, crystal-clear Black Sea blend tea brewed in traditional copper samovars. Followed by slow-cooked foamy Turkish coffee brewed over hot embers and freshly squeezed juices.",
          image: "/images/coffee-moment.webp",
          badge: "Endless Tea",
          tag: "Always Steaming",
        },
      ],
    },
    venue: {
      badge: "Grade II Registered Historic Landmark",
      title: "Memorable Moments Await You!",
      subtitle: "Beyoğlu's enchanting historic atmosphere meets generous Van breakfast flavors.",
      description:
        "Tarihi Van Kahvaltı Evi proudly presents the rich culinary heritage of the East in our historic 19th-century Greek mansion in Beyoğlu. High ceilings, carved antique mirrors, and the authentic vibe of Zambak Street await you for a timeless breakfast experience.",
      callAction: "Call Us",
      menuAction: "Explore Live Menu",
      reservationAction: "Book a Table",
    },
    reviews: {
      eyebrow: "Guest notes",
      title: "Through our",
      titleAccent: "guests' eyes.",
      intro: "This time, our guests tell the story of the table, the flavours and the character of our home.",
      googleLabel: "Google reviews",
      rating: "4.9",
      ratingLabel: "Average rating out of 5",
      count: "1,316 guest reviews",
      viewAll: "See all reviews on Google",
      previous: "Show previous review",
      next: "Show next review",
      choose: "Show this review",
      photoLabel: "A moment from the restaurant",
      reviews: [
        {
          name: "AZRA KAPKAÇ",
          time: "6 days ago",
          quote: "Kesinlikle 5 yıldızı hak eden bir mekan! Her şey çok taze, lezzetli ve özenle hazırlanmıştı. Çeşit bolluğu ve ürünlerin kalitesi tek kelimeyle harikaydı. Ayrıca çalışanların güler yüzlü ve hızlı hizmeti de ortamın sıcaklığını iki katına çıkartıyorrr. Güne mutlu ve enerjik başlamak için bundan daha iyi bir adres olamaz. Gönül rahatlığıyla tavsiye ediyorum",
          photo: "/images/interior-chair.webp",
          alt: "The restaurant's vintage telephone, armchair and flowers",
        },
        {
          name: "Emine Pektaş",
          time: "22 hours ago",
          quote: "Harika🫨🩷",
          photo: "/images/balcony-breakfast.webp",
          alt: "A Van breakfast table set on the historic building's balcony",
        },
        {
          name: "bahar özkan",
          time: "1 day ago",
          quote: "çok iyiydi gerçekten puanı çok yüksek diye şaşırmıştık genelde bu puanlarda restoran bulmak çok zor. ama her bir puanı hak ediyor. çalışanlar çok güler yüzlü nazik ve kibar. teşekkür ederiz",
          photo: "/images/interior-chair.webp",
          alt: "The restaurant's vintage telephone, armchair and flowers",
        },
        {
          name: "Ezgi Asikoglu",
          time: "5 days ago",
          quote: "Her şey çok güzeldi. Güleryüzlü nazik insanlar. Keyifli vakit geçirdik",
          photo: "/images/breakfast-spread.webp",
          alt: "A Van breakfast with copper pans and regional cheeses",
        },
        {
          name: "Zeynep Kadirağagil",
          time: "5 days ago",
          quote: "güzeldi teşekkürler",
          photo: "/images/street-table.webp",
          alt: "A breakfast table set along the street frontage",
        },
        {
          name: "Muaz Maciter",
          time: "6 days ago",
          quote: "Ahmet kardeşimize hizmetinden ötürü teşekkür ederiz…",
          photo: "/images/terrace-tea.webp",
          alt: "Tea and breakfast served on the terrace",
        },
        {
          name: "Metehan Çelik",
          time: "6 days ago",
          quote: "Yemekler ve hizmet çok iyiydi. Kesinlikle tavsiye ederim. Bizimle ilgilenen Ahmet kardeşime ilgisinden dolayı teşekkür ederim.",
          photo: "/images/tea-service.webp",
          alt: "Freshly brewed Turkish tea being served",
        },
        {
          name: "Metehan",
          time: "6 days ago",
          quote: "Ahmet bizimle çok iyi ilgilendi. Her şey çok iyiydi.",
          photo: "/images/hands-table.webp",
          alt: "Regional dishes being shared around the breakfast table",
        },
        {
          name: "Hamza Maciter",
          time: "6 days ago",
          quote: "Ahmet beye çok teşekkür ederiz her şey süperdi",
          photo: "/images/balcony-breakfast.webp",
          alt: "A Van breakfast table set on the historic building's balcony",
        },
        {
          name: "mirza ayhan",
          time: "6 days ago",
          quote: "Mükemmel kahvaltı her şey taze hizmet mükemmel Ahmet kardeşimize alakasından dolayı teşekkür ederiz.",
          photo: "/images/interior-chair.webp",
          alt: "The restaurant's vintage telephone, armchair and flowers",
        },
        {
          name: "hilal yavuz",
          time: "6 days ago",
          quote: "çok teşekkürler",
          photo: "/images/breakfast-spread.webp",
          alt: "A Van breakfast with copper pans and regional cheeses",
        },
        {
          name: "Tulay Durmaz",
          time: "6 days ago",
          quote: "Guzel kahvalti samet bey tatli dilli hizmetliydi guzel devam",
          photo: "/images/street-table.webp",
          alt: "A breakfast table set along the street frontage",
        },
        {
          name: "Ömer",
          time: "6 days ago",
          quote: "Ferdi beye bizimle ilgilendiği için teşekkür ederiz her yolumuz düştüğünde uğrayacağız❤️❤️❤️",
          photo: "/images/terrace-tea.webp",
          alt: "Tea and breakfast served on the terrace",
        },
        {
          name: "Emrah Güneysu",
          time: "6 days ago",
          quote: "Kahvaltı çok güzeldi. Ferdi bey bizimle çok iyi ilgilendi. Tekrar yolumuz düşerse kesinlikle uğranması gereken bir yer",
          photo: "/images/tea-service.webp",
          alt: "Freshly brewed Turkish tea being served",
        },
        {
          name: "Hüseyin Memiş",
          time: "6 days ago",
          quote: "Ferdi bey teşekkür  ederim bizimle baya ilgilendi kahvaltı gerçekten çok güzeldi",
          photo: "/images/hands-table.webp",
          alt: "Regional dishes being shared around the breakfast table",
        },
        {
          name: "Ahmet egüz",
          time: "6 days ago",
          quote: "Kahvaltısı harikaydı herkese öneririm  Ferdi beye teşekkür ederiz",
          photo: "/images/balcony-breakfast.webp",
          alt: "A Van breakfast table set on the historic building's balcony",
        },
        {
          name: "Duygu Dogan",
          time: "6 days ago",
          quote: "Kahvaltı süper tekrar teşekkürler 👍🏼",
          photo: "/images/breakfast-spread.webp",
          alt: "A Van breakfast with copper pans and regional cheeses",
        },
        {
          name: "Serpil İlhan",
          time: "1 week ago",
          quote: "Çok iyi hizmet.",
          photo: "/images/street-table.webp",
          alt: "A breakfast table set along the street frontage",
        },
        {
          name: "Ayşe Akın",
          time: "1 week ago",
          quote: "Ailecek,Akrabalarınızla ve Arkadaşlarınızla gelebileceğiniz harika bir yer..Biz geldik ve çok beğendik atmosfer olsun yemeklerin tadı olsun herşey harikaydı....",
          photo: "/images/terrace-tea.webp",
          alt: "Tea and breakfast served on the terrace",
        },
        {
          name: "Zekiye Deniz",
          time: "1 week ago",
          quote: "Herşey cok güzeldi ilgi alaka mükemmledi ellerinize sağlık",
          photo: "/images/tea-service.webp",
          alt: "Freshly brewed Turkish tea being served",
        },
      ],
    },
    gallery: {
      title: "Around",
      titleAccent: "our table",
      booking: "Request a table",
      aria: "Restaurant and breakfast gallery",
      close: "Close gallery",
      previous: "Previous photo",
      next: "Next photo",
      view: "View photo",
      images: [
        ["/images/balcony-breakfast.webp", "Van breakfast served on the balcony"],
        ["/images/sucuk-egg.webp", "Hot eggs with sucuk in a copper pan"],
        ["/images/hands-table.webp", "Friends sharing dishes across the breakfast table"],
        ["/images/interior-chair.webp", "Historic details inside the Beyoğlu restaurant"],
        ["/images/tea-service.webp", "Fresh Turkish tea served throughout breakfast"],
        ["/images/breakfast-spread.webp", "A generous traditional Van breakfast spread"],
        ["/images/historic-mirror.webp", "The restaurant's ornate historic mirror"],
        ["/images/terrace-tea.webp", "Turkish tea and breakfast on the terrace"],
        ["/images/coffee-moment.webp", "A coffee break at Kafka Cafe"],
        ["/images/street-table.webp", "Breakfast tables on Zambak Street in Beyoğlu"],
      ],
    },
    faq: {
      eyebrow: "Before you visit",
      title: "Visitor questions",
      intro: "Practical answers about our traditional Turkish breakfast near Taksim.",
      items: englishFaqItems,
    },
    footer: {
      sceneAria: "A nostalgic İstiklal Avenue tram, Galata Tower and the historic Beyoğlu skyline",
      backToTop: "Back to top",
      manifesto: "A Van breakfast,",
      manifestoEmphasis: "served with a sense of history.",
      description:
        "Our family story began in 1978. Today, the texture of a historic Beyoğlu building meets the sound of copper pans and an ever-fresh pot of Turkish tea.",
      booking: "Request a Table",
      explore: "Explore",
      exploreLinks: [
        ["/en/rezervasyon", "Table Reservation"],
        ["/en/menu", "Live English Menu"],
        ["/en/blog/turkish-breakfast-istanbul", "Complete Turkish Breakfast Guide"],
        ["/ru/blog/turetskiy-zavtrak-stambul", "Русский гид"],
        ["/ar/blog/turkish-breakfast-istanbul", "الدليل العربي"],
        ["/ko", "한국어 카이막·아침 식사 가이드"],
        ["/ja/blog/istanbul-bal-kaymak", "日本語バル・カイマクガイド"],
        ["/en#story", "What Makes a Van Breakfast"],
        ["/en#story", "Our Story Since 1978"],
        ["https://www.google.com/maps?cid=10380797280962926014", "Directions from Taksim"],
        ["/en/menu#icecekler", "Tea & Kafka Cafe"],
        ["/en#faq", "Visitor Questions"],
        ["/", "Türkçe Site"],
      ],
      contact: "Contact",
      whatsapp: "Ask on WhatsApp",
      listedTitle: "Grade II",
      listedSubtitle: "Historic Building",
      hours: "Open Every Day",
      copyright: "© 2026 Tarihi Van Kahvaltı Evi. All rights reserved.",
      privacy: "Privacy policy (Turkish)",
      cookies: "Cookie policy (Turkish)",
    },
  },
} as const;

export function messagesFor(locale: SiteLocale) {
  return homeMessages[locale];
}
